In [2]:
import os
import pandas as pd
from decimal import Decimal
import numpy as np
from datetime import datetime, timedelta
from dotenv import load_dotenv
import yfinance as yf


import matplotlib.pyplot as plt
import plotly.express as px
import pytz  # Make sure to import pytz for timezone handling
import seaborn as sns
from sklearn.linear_model import LinearRegression

import requests
import csv
import json

import warnings

In [3]:
load_dotenv()

API_KEY = os.getenv("alpha_vantage_api_key")

In [4]:
# Addtional setting session
# Set display options to show all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")
pd.options.mode.copy_on_write = True

# PE TTM valuation

In [5]:
# Parameters section

alpha_vantage_api_key = API_KEY # FREE TIER API rate limit is 25 requests per day
alpha_vantage_function = {
    'core':[
        'TIME_SERIES_INTRADA'
        ,'TIME_SERIES_DAILY' # this is daily time series quote
        ,'TIME_SERIES_DAILY_ADJUSTED' # this is daily time series adjusted by split/dividend-adjusted
        ,'GLOBAL_QUOTE'
    ]
    ,'fundmental':[
    'INCOME_STATEMENT'
    ,'BALANCE_SHEET' # this is daily time series quote
    ,'CASH_FLOW' # this is daily time series adjusted by split/dividend-adjusted
    ,'EARNINGS'
    ,'EARNINGS_CALENDAR'
]
}

# # Custmized
# ticker_symbols = [

#     'CL'
#     ,'ACN'
#     # ,'GOOG'
#     # ,'TSM'
#     # ,'META'
#     # ,'LPG'
#     # ,'NVDA'
#     # ,'SKWD'
#     ,'MSFT'
#     # ,'NFLX'
#     # ,'V'
#     # ,'PG'
#     ,'INTU'
#     # ,'ISRG'
#     ]

ticker_symbols = [
 'MO',
 'ADM',
#  'BF.B',
 'BG',
 'CPB',
 'CHD',
 'CLX',
 'KO',
 'CL',
 'CAG',
 'STZ',
 'COST',
 'DG',
 'DLTR',
 'EL',
 'GIS',
 'HSY',
 'HRL',
#  'KVUE',
 'KDP',
 'KMB',
 'KHC',
 'KR',
 'LW',
 'MKC',
 'TAP',
 'MDLZ',
 'MNST',
 'PEP',
 'PM',
 'PG',
 'SJM',
 'SYY',
 'TGT',
 'TSN',
#  'WBA',
 'WMT'
 ]


# Time intelligent parameters
window_days = 90
end_date = datetime.now()
start_date = end_date - timedelta(days=window_days)
earning_calendar = [
    3  # this will return next 1 qtr forecast earning; nowadays the earning calendar only shows the next 1 qtr forecast earning
    ,6  # this will return next 2 qtr forecast earning
    ,12  # this will return next 4 qtr forecast earning
]

PE_yr_range = 9 # this will return x-1 yr PE range, cuz you cannot get current year end PE

ticker_dict_json = {}
ticker_dict_pd = {}

In [6]:
def convert_to_numeric_or_zero(value):
    try:
        # Try to convert the string to a float (or int)
        num = round(float(value), 2)
        return num  # Return the original value if it can be converted to a number
    except ValueError:
        # If conversion fails, return '0'
        return 0

In [7]:
# Daily quote section
for j, symbol in enumerate(ticker_symbols):

    print(j, symbol)
    # STOCK SPLIT FACTOR section
    url = f'https://www.alphavantage.co/query?function=SPLITS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'data':
            if len(value) > 0:
                stock_split_record_df = pd.DataFrame(value)
                stock_split_record_df['split_factor'] = pd.to_numeric(stock_split_record_df['split_factor'], errors='coerce') # change split_factor series to numeric data
                stock_split_record_df['effective_date'] = pd.to_datetime(stock_split_record_df['effective_date'])
            else:
                # Use pandas index assign instead of direct assign value
                stock_split_record_df = pd.DataFrame({
                'split_factor': [1],
                'effective_date': [datetime.today()]
            })
                # stock_split_record_df = pd.DataFrame()
                # stock_split_record_df['split_factor'] = 1
                # stock_split_record_df['effective_date'] = datetime.today()


    # Daily quote section
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={alpha_vantage_api_key}&outputsize=full'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'Time Series (Daily)':


            selected_cols = [
                '4. close'
            ]

            Daily_stock_df = pd.DataFrame(value).transpose()[selected_cols] # tranpose the dataframe and sub select selected cols

            # Rename columns
            Daily_stock_df.rename(
                columns={
                    '4. close': 'stock_price'
                    }
                ,inplace=True
                )
            
            Daily_stock_df["stock_price"] = Daily_stock_df["stock_price"].astype(str).apply(lambda x: float(x))
            Daily_stock_df["stock_price"] = Daily_stock_df["stock_price"].round(2)
            Daily_stock_df.index = pd.to_datetime(Daily_stock_df.index)


    for date_i in Daily_stock_df.index.date:
        for date_j in stock_split_record_df['effective_date'].dt.date:
            if date_i == date_j:

                # stock price to divided the split factor
                Daily_stock_df.loc[Daily_stock_df.index.date < date_j, 'stock_price'] /= (stock_split_record_df['split_factor'][stock_split_record_df['effective_date'].dt.date == date_j].values[0])


    # MA200 calculation
    Daily_stock_df['MA200'] = Daily_stock_df.sort_index(ascending=True)['stock_price'].rolling(window=200).mean()

    # Calculate the slope of the MA200 using linear regression
    def calculate_slope(series):
        # Create a time index (0, 1, 2, ..., n) for the linear regression
        x = np.arange(len(series)).reshape(-1, 1)
        y = series.values.reshape(-1, 1)

        # Fit the linear regression model
        model = LinearRegression()
        model.fit(x, y)

        # Return the slope
        return model.coef_[0][0]


    # Apply the slope calculation to the MA200 values
    Daily_stock_df['MA200_slope'] = Daily_stock_df.sort_index(ascending=True)['MA200'].rolling(window=20).apply(calculate_slope, raw=False)



    # Monthly quote section
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'Monthly Time Series':
            Monthly_stock_df = pd.DataFrame(value)

    Monthly_stock_df = Monthly_stock_df.transpose()
    Monthly_stock_df.index = pd.to_datetime(Monthly_stock_df.index)


    filter_1 = (Monthly_stock_df.index.year.isin(range((datetime.today().year - PE_yr_range) ,datetime.today().year)))
    filter_2 = (Monthly_stock_df.index.month == 12) # month = 12 to get the year end closing price

    selected_cols = [
        '4. close'
    ]

    Monthly_stock_df = Monthly_stock_df[
        filter_1
        & filter_2
    ][selected_cols]

    # Rename columns
    Monthly_stock_df.rename(
        columns={
            '4. close': 'stock_price'
            }
        ,inplace=True
        )

    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].astype(str).apply(lambda x: float(x))
    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].round(2)

    # modify stock price based on stock split
    for year_i in Monthly_stock_df.index.year:
        for year_j in stock_split_record_df['effective_date'].dt.year:
            if year_i == year_j:

                # stock price to divided the split factor
                Monthly_stock_df.loc[Monthly_stock_df.index.year < year_j, 'stock_price'] /= (stock_split_record_df['split_factor'][stock_split_record_df['effective_date'].dt.year == year_j].values[0])



    # Earning section
    # past earnings from alpha vintage API
    url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'annualEarnings':

            selected_cols = [
                'fiscalDateEnding'
                ,'reportedEPS'
            ]

            annualEPS_df = pd.DataFrame(value) # tranpose the dataframe and sub select selected cols


            annualEPS_df['fiscalDateEnding'] = pd.to_datetime(annualEPS_df['fiscalDateEnding']).dt.year

            annualEPS_df = annualEPS_df[
                annualEPS_df['fiscalDateEnding'].isin(
                    range(
                        (datetime.today().year - PE_yr_range) 
                        ,datetime.today().year
                            )
                            )
                            ]

            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    annualEPS_df[f'{col}'] = annualEPS_df[f'{col}'].astype(str).apply(lambda x: float(x))

                else:
                    continue
            
            # clean annualEPS_df
            annualEPS_df = annualEPS_df.sort_values('reportedEPS', ascending=False).drop_duplicates('fiscalDateEnding')
            annualEPS_df = annualEPS_df.sort_values('fiscalDateEnding', ascending=False).reset_index(drop=True)

            # calculate metrics
            if Monthly_stock_df.shape[0] <= annualEPS_df.shape[0]: # if Monthly_stock_df has less records than annualEPS_df, choose the mini length record
                annualEPS_df = annualEPS_df[:(Monthly_stock_df.shape[0])]

                annualEPS_df["PE"] = Monthly_stock_df["stock_price"].values / annualEPS_df['reportedEPS'].values
                annualEPS_df[f"PE_{PE_yr_range-1}yr_avg"] = annualEPS_df["PE"].mean().round(2)
                annualEPS_df[f"PE_{PE_yr_range-1}yr_std"] = np.std(annualEPS_df["PE"]).round(2)
                annualEPS_df[f"PE_{PE_yr_range-1}yr_volatility_+"] = (annualEPS_df[f"PE_{PE_yr_range-1}yr_avg"] + annualEPS_df[f"PE_{PE_yr_range-1}yr_std"]).round(2) # 这个是PE的波动范围上限
                annualEPS_df[f"PE_{PE_yr_range-1}yr_volatility_-"] = (annualEPS_df[f"PE_{PE_yr_range-1}yr_avg"] - annualEPS_df[f"PE_{PE_yr_range-1}yr_std"]).round(2) # 这个是PE的波动范围下限



        if key == 'quarterlyEarnings':

            selected_cols = [
                'reportedDate'
                ,'reportedEPS'
            ]

            qtrEPS_df = pd.DataFrame(value)[selected_cols] # tranpose the dataframe and sub select selected cols
            qtrEPS_df['reportedDate'] = pd.to_datetime(qtrEPS_df['reportedDate'])

            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    qtrEPS_df[col] = qtrEPS_df[col].astype(str).apply(lambda x: float(x) if x not in [None, 'None', 'nan', 'NaN'] else float(0))
                else:
                    continue


    # # forecast 1 qtr earnings from alpha vantage API -- for now we use yf API
    # # for i in earning_calendar: comment out the for loop in case of future usage, i can be the parameter of {}month
    # CSV_URL = f'https://www.alphavantage.co/query?function=EARNINGS_CALENDAR&symbol={symbol}&horizon=12month&apikey={alpha_vantage_api_key}'
    # with requests.Session() as s:
    #     download = s.get(CSV_URL)
    #     decoded_content = download.content.decode('utf-8')
    #     cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    #     my_list = list(cr)

    #     forecast_earanings_df = pd.DataFrame(
    #         columns=my_list[0]
    #         ,data=my_list[1::]
    #         )
        
    #     if forecast_earanings_df['estimate'].head(1).values != '':
    #         latest_projected_EPS = float(forecast_earanings_df['estimate'].head(1).values)
    #     else:
    #         latest_projected_EPS = 0


    # forecast 1 qtr earning, 1yr earning from yf API
    yf_symbol = yf.Ticker(symbol)
    stock_eps_forecast_df = yf_symbol.earnings_estimate
    stock_eps_forecast_df['period'] = stock_eps_forecast_df.index
    next_qtr_EPS = stock_eps_forecast_df[stock_eps_forecast_df['period'] == '+1q']['avg'].values[0]
    # next yr eps
    next_yr_EPS = stock_eps_forecast_df[stock_eps_forecast_df['period'] == '+1y']['avg'].values[0]


    # EPS trend from yf API
    stock_eps_trend_df = yf_symbol.eps_trend
    stock_eps_trend_df['period'] = stock_eps_trend_df.index
    next_yr_days7ago_EPS = stock_eps_trend_df[stock_eps_trend_df['period'] == '+1y']['7daysAgo'].values[0]
    next_yr_days30ago_EPS = stock_eps_trend_df[stock_eps_trend_df['period'] == '+1y']['30daysAgo'].values[0]
    next_yr_days60ago_EPS = stock_eps_trend_df[stock_eps_trend_df['period'] == '+1y']['60daysAgo'].values[0]
    next_yr_days90ago_EPS = stock_eps_trend_df[stock_eps_trend_df['period'] == '+1y']['90daysAgo'].values[0]



    # stock growth rate from yf API
    stock_growth_est_df = yf_symbol.growth_estimates
    stock_growth_est_df['period'] = stock_growth_est_df.index
    curr_yr_growthrate_symbol = stock_growth_est_df[stock_growth_est_df['period'] == '0y']['stockTrend'].values[0] * 100
    next_yr_growthrate_symbol = stock_growth_est_df[stock_growth_est_df['period'] == '+1y']['stockTrend'].values[0] * 100
    curr_yr_growthrate_index = stock_growth_est_df[stock_growth_est_df['period'] == '0y']['indexTrend'].values[0] * 100
    next_yr_growthrate_index = stock_growth_est_df[stock_growth_est_df['period'] == '+1y']['indexTrend'].values[0] * 100


    # US Treasury section
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=TREASURY_YIELD&interval=daily&maturity=10year&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'data':
            US_T_10yrs_df = pd.DataFrame(value)
            US_T_10yrs_df['value'] = pd.to_numeric(US_T_10yrs_df['value'], errors='coerce') # change dataframe value to numeric data
            US_T_10yrs_YTM = US_T_10yrs_df['value'][0]



    # COMPANY OVERVIEW
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    
    for key, value in data.items():
        if key  == 'MarketCapitalization':
            stock_mkt_cap = float(value)



    # INCOME STATEMENT
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()


    for key, value in data.items():
        if key == 'annualReports':
            annual_income_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_income_df = annual_income_df.sort_values('fiscalDateEnding', ascending=True)

            # annual measurements cols
            annual_income_metric_cols = annual_income_df.columns[1:]

            # Calculate quarter-over-quarter change percentage
            for column in annual_income_metric_cols:  # Exclude the 'fiscalDateEnding' column
                annual_income_df[column] = pd.to_numeric(annual_income_df[column], errors='coerce')
                annual_income_df[f'{column}_YoY'] = annual_income_df[column].pct_change() * 100 
            
            annual_income_YoY_metric_cols = [col for col in annual_income_df.columns if 'YoY' in col]

            # ratios of income statement calculation
            annual_income_df['gross_margin_%'] = (annual_income_df['grossProfit'] / annual_income_df['totalRevenue']) * 100
            annual_income_df['operating_margin_%'] = (annual_income_df['operatingIncome'] / annual_income_df['totalRevenue']) * 100
            annual_income_df['net_margin_%'] = (annual_income_df['netIncome'] / annual_income_df['totalRevenue']) * 100



        if key == 'quarterlyReports':
            qtr_income_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_income_df = qtr_income_df.sort_values('fiscalDateEnding', ascending=True)

            # qtr measurements cols
            qtr_income_metric_cols = qtr_income_df.columns[1:]
            
            # Calculate quarter-over-quarter change percentage
            for column in qtr_income_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_income_df[column] = pd.to_numeric(qtr_income_df[column], errors='coerce')
                qtr_income_df[f'{column}_QoQ'] = qtr_income_df[column].pct_change() * 100

            qtr_income_QoQ_metric_cols = [col for col in qtr_income_df.columns if 'QoQ' in col]

            # ratios of income statement calculation
            qtr_income_df['gross_margin_%'] = (qtr_income_df['grossProfit'] / qtr_income_df['totalRevenue']) * 100
            qtr_income_df['operating_margin_%'] = (qtr_income_df['operatingIncome'] / qtr_income_df['totalRevenue']) * 100
            qtr_income_df['net_margin_%'] = (qtr_income_df['netIncome'] / qtr_income_df['totalRevenue']) * 100

    income_ratio_cols = [
        'gross_margin_%'
        ,'operating_margin_%'
        ,'net_margin_%'
        ,'netIncome'
        ]
    
    

    # BALANCESHEET
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():

        if key == 'annualReports':
            annual_balancesheet_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_balancesheet_df = annual_balancesheet_df.sort_values('fiscalDateEnding', ascending=True)

            for column in annual_balancesheet_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                annual_balancesheet_df[column] = pd.to_numeric(annual_balancesheet_df[column], errors='coerce')

            annual_balancesheet_df['current_ratio'] = (annual_balancesheet_df['totalCurrentAssets'] / annual_balancesheet_df['totalCurrentLiabilities'])
            annual_balancesheet_df['working_capital'] = annual_balancesheet_df['totalCurrentAssets'] - annual_balancesheet_df['totalCurrentLiabilities']
            annual_balancesheet_df['longTermDebt_to_workingCp_ratio'] = (annual_balancesheet_df['longTermDebt'] / annual_balancesheet_df['working_capital'])
            annual_balancesheet_df['debtEquity_ratio'] = (annual_balancesheet_df['totalLiabilities'] / annual_balancesheet_df['totalShareholderEquity'])
            annual_balancesheet_df['quick_ratio'] = ((annual_balancesheet_df['totalCurrentAssets'] - annual_balancesheet_df['inventory']) / annual_balancesheet_df['totalCurrentLiabilities'])

            
        if key == 'quarterlyReports':
            qtr_balancesheet_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_balancesheet_df = qtr_balancesheet_df.sort_values('fiscalDateEnding', ascending=True)

            for column in qtr_balancesheet_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_balancesheet_df[column] = pd.to_numeric(qtr_balancesheet_df[column], errors='coerce')

    
            qtr_balancesheet_df['current_ratio'] = (qtr_balancesheet_df['totalCurrentAssets'] / qtr_balancesheet_df['totalCurrentLiabilities'])
            qtr_balancesheet_df['working_capital'] = qtr_balancesheet_df['totalCurrentAssets'] - qtr_balancesheet_df['totalCurrentLiabilities']
            qtr_balancesheet_df['longTermDebt_to_workingCp_ratio'] = (qtr_balancesheet_df['longTermDebt'] / qtr_balancesheet_df['working_capital'])
            qtr_balancesheet_df['debtEquity_ratio'] = (qtr_balancesheet_df['totalLiabilities'] / qtr_balancesheet_df['totalShareholderEquity'])
            qtr_balancesheet_df['quick_ratio'] = ((qtr_balancesheet_df['totalCurrentAssets'] - qtr_balancesheet_df['inventory']) / qtr_balancesheet_df['totalCurrentLiabilities'])

            qtr_balancesheet_df['BVPS_latest'] = round(
                qtr_balancesheet_df.tail(1)['totalShareholderEquity'].sum() / qtr_balancesheet_df.tail(1)['commonStockSharesOutstanding']
                ,2
                )



    balancesheet_ratio_cols = [
        'current_ratio'
        ,'working_capital'
        ,'longTermDebt_to_workingCp_ratio'
        ,'debtEquity_ratio'
        ,'quick_ratio'
        ,'totalShareholderEquity'
    ]


    # CASHFLOW STATEMENT
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=CASH_FLOW&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():

        if key == 'annualReports':
            annual_cashflow_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_cashflow_df = annual_cashflow_df.sort_values('fiscalDateEnding', ascending=True)

            for column in annual_cashflow_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                annual_cashflow_df[column] = pd.to_numeric(annual_cashflow_df[column], errors='coerce')
                annual_cashflow_df[f'{column}_YoY'] = annual_cashflow_df[column].pct_change() * 100

            
        if key == 'quarterlyReports':
            qtr_cashflow_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_cashflow_df = qtr_cashflow_df.sort_values('fiscalDateEnding', ascending=True)

            for column in qtr_cashflow_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_cashflow_df[column] = pd.to_numeric(qtr_cashflow_df[column], errors='coerce')
                qtr_cashflow_df[f'{column}_YoY'] = qtr_cashflow_df[column].pct_change() * 100


    stock_ratios_annual_consolidate_df = pd.DataFrame()
    stock_ratios_qtr_consolidate_df = pd.DataFrame()

    stock_ratios_annual_consolidate_df[income_ratio_cols] = annual_income_df[income_ratio_cols]
    stock_ratios_annual_consolidate_df[balancesheet_ratio_cols] = annual_balancesheet_df[balancesheet_ratio_cols]

    stock_ratios_qtr_consolidate_df[income_ratio_cols] = qtr_income_df[income_ratio_cols]
    stock_ratios_qtr_consolidate_df[balancesheet_ratio_cols] = qtr_balancesheet_df[balancesheet_ratio_cols]

    # calculating new consolidated metrics 
    # annual df
    stock_ratios_annual_consolidate_df['ROE_%'] = (annual_income_df['netIncome'] / annual_balancesheet_df['totalShareholderEquity']) * 100
    stock_ratios_annual_consolidate_df['liquidation_value'] = ((annual_balancesheet_df['totalAssets'] - annual_balancesheet_df['intangibleAssets']) - annual_balancesheet_df['totalLiabilities'])
    # stock_ratios_annual_consolidate_df['liquidation_mktcap_ratio_%'] = round((stock_ratios_annual_consolidate_df['liquidation_value'] / stock_mkt_cap) * 100, 2)
    stock_ratios_annual_consolidate_df['fiscalDateEnding'] = annual_balancesheet_df['fiscalDateEnding']

    # qtr df
    stock_ratios_qtr_consolidate_df['ROE_%'] = (qtr_income_df['netIncome'] / qtr_balancesheet_df['totalShareholderEquity']) * 100
    stock_ratios_qtr_consolidate_df['liquidation_value'] = ((qtr_balancesheet_df['totalAssets'] - qtr_balancesheet_df['intangibleAssets']) - qtr_balancesheet_df['totalLiabilities'])
    # stock_ratios_qtr_consolidate_df['liquidation_mktcap_ratio_%'] = round((stock_ratios_qtr_consolidate_df['liquidation_value'] / stock_mkt_cap) * 100, 2)
    stock_ratios_qtr_consolidate_df['fiscalDateEnding'] = qtr_balancesheet_df['fiscalDateEnding']





    # Consolidated section
    stock_consolidate_df = Daily_stock_df.head(window_days)


    stock_consolidate_df_date = stock_consolidate_df.index
    for i in stock_consolidate_df_date:
                
        # Filter the DataFrame to include only dates(index) less than or equal to the target date
        filtered_qtrEPS_df = qtrEPS_df[qtrEPS_df['reportedDate'] < i]

        # Select the first four rows from the past_qtrs_EPS
        past_4_qtrs_EPS = filtered_qtrEPS_df.head(4) 
        past_3_qtrs_EPS = filtered_qtrEPS_df.head(3)
        past_1_qtr_EPS = filtered_qtrEPS_df.head(1)

        # Calculate the sum of the numeric values in the selected rows
        EPS_TTM = past_4_qtrs_EPS['reportedEPS'].values.sum()
        EPS_curr_qtr = past_1_qtr_EPS['reportedEPS'].values.sum()

        # assign each index row with the EPS_TTM
        stock_consolidate_df.loc[i, "EPS_TTM"] = EPS_TTM
        stock_consolidate_df.loc[i, "EPS_currentQtr"] = EPS_curr_qtr

        if i == max(stock_consolidate_df.index):
            EPS_nextQtr_projected = next_qtr_EPS + past_3_qtrs_EPS['reportedEPS'].values.sum()  # This metrics is the past 3 qtrs post EPS + 1 projected EPS
        else:
            continue

        stock_consolidate_df["EPS_nextQtr"] = next_qtr_EPS
        stock_consolidate_df["EPS_nextQtr_TTM"] = EPS_nextQtr_projected
        stock_consolidate_df["EPS_nextYr"] = next_yr_EPS

    

    # stock's stats
    stock_consolidate_df["Ticker"] = symbol
    # stock_consolidate_df["PE_1yr_forward"] = round(PE_12month_projected, 2)
    stock_consolidate_df["PE_TTM"] = (stock_consolidate_df["stock_price"] / stock_consolidate_df["EPS_TTM"]).round(2)
    stock_consolidate_df["PE_TTM_avg"] = stock_consolidate_df["PE_TTM"].mean().round(2)
    stock_consolidate_df["PE_TTM_std"] = np.std(stock_consolidate_df["PE_TTM"]).round(2)
    stock_consolidate_df["PE_TTM_volatility_+"] = (stock_consolidate_df["PE_TTM_avg"] + stock_consolidate_df["PE_TTM_std"]).round(2) # 这个是PE的波动范围上限
    stock_consolidate_df["PE_TTM_volatility_-"] = (stock_consolidate_df["PE_TTM_avg"] - stock_consolidate_df["PE_TTM_std"]).round(2) # 这个是PE的波动范围下限

    stock_consolidate_df["relative_valuation_TTM_+"] = (stock_consolidate_df["PE_TTM_volatility_+"] * stock_consolidate_df["EPS_TTM"]).round(2) # 这个是relative valuation的价格上限
    stock_consolidate_df["relative_valuation_TTM_-"] = (stock_consolidate_df["PE_TTM_volatility_-"] * stock_consolidate_df["EPS_TTM"]).round(2) # 这个是relative valuation的价格下限
    stock_consolidate_df["relative_valuation_TTM_median"] = (np.median([stock_consolidate_df["relative_valuation_TTM_+"][0], stock_consolidate_df["relative_valuation_TTM_-"][0]])).round(2) #这个是根据最新TTM PE估值的价格中位数

    stock_consolidate_df["relative_valuation_nextQuater_projected_+"] = (stock_consolidate_df["PE_TTM_volatility_+"] * stock_consolidate_df["EPS_nextQtr_TTM"]).round(2) # 这个是relative valuation的价格上限
    stock_consolidate_df["relative_valuation_nextQuater_projected_-"] = (stock_consolidate_df["PE_TTM_volatility_-"] * stock_consolidate_df["EPS_nextQtr_TTM"]).round(2) # 这个是relative valuation的价格下限
    stock_consolidate_df["relative_valuation_nextQuater_projected_median"] = (np.median([stock_consolidate_df["relative_valuation_nextQuater_projected_+"][0], stock_consolidate_df["relative_valuation_nextQuater_projected_-"][0]])).round(2) #这个是根据3 qtrs post EPS + 1 projected EPS 得出PE估值的价格中位数

    stock_consolidate_df[f"{window_days}_price_min"] = stock_consolidate_df["stock_price"].min().round(2)
    stock_consolidate_df[f"{window_days}_price_max"] = stock_consolidate_df["stock_price"].max().round(2)
    stock_consolidate_df[f"{window_days}_price_avg"] = stock_consolidate_df["stock_price"].mean().round(2)
    stock_consolidate_df[f"{window_days}_price_std"] = np.std(stock_consolidate_df["stock_price"]).round(2)

    stock_consolidate_df[f"PE_{PE_yr_range-1}yr_avg"] = annualEPS_df[f"PE_{PE_yr_range-1}yr_avg"].values[0]
    stock_consolidate_df[f"PE_{PE_yr_range-1}yr_std"] = annualEPS_df[f"PE_{PE_yr_range-1}yr_std"].values[0]
    stock_consolidate_df[f"PE_{PE_yr_range-1}yr_volatility_+"] = annualEPS_df[f"PE_{PE_yr_range-1}yr_volatility_+"].values[0]
    stock_consolidate_df[f"PE_{PE_yr_range-1}yr_volatility_-"] = annualEPS_df[f"PE_{PE_yr_range-1}yr_volatility_-"].values[0]


    stock_consolidate_df["relative_valuation_nextYear_projected_+"] = (stock_consolidate_df["PE_TTM_volatility_+"] * next_yr_EPS).round(2) # 这个是relative valuation的价格上限
    stock_consolidate_df["relative_valuation_nextYear_projected_-"] = (stock_consolidate_df["PE_TTM_volatility_-"] * next_yr_EPS).round(2) # 这个是relative valuation的价格下限
    stock_consolidate_df["relative_valuation_nextYear_projected_median"] = (np.median([stock_consolidate_df["relative_valuation_nextYear_projected_+"][0], stock_consolidate_df["relative_valuation_nextYear_projected_-"][0]])).round(2) #这个是根据next year projected EPS 得出PE估值的价格中位数

    # stock_consolidate_df["PEG_next12months"] = PEG_12month_projected
    stock_consolidate_df["EPS_nextYr"] = round(next_yr_EPS, 2)
    # stock_consolidate_df["PEG_TTM"] = (stock_consolidate_df["PE_TTM"] / (((next_yr_EPS - stock_consolidate_df["EPS_TTM"]) / stock_consolidate_df["EPS_TTM"]) * 100)).round(2) # 这个是截止下一年的EPS growth rate所得出的PEG ratio, <1是undervalue的表现
    
    stock_consolidate_df["EPS_nextYr_growthRate"] = (((next_yr_EPS - stock_consolidate_df["EPS_TTM"]) / stock_consolidate_df["EPS_TTM"]) * 100).round(2)
    stock_consolidate_df["EPS_nextQtr_growthRate"] = (((stock_consolidate_df["EPS_nextQtr_TTM"] - stock_consolidate_df["EPS_TTM"]) / stock_consolidate_df["EPS_TTM"]) * 100).round(2)

    stock_consolidate_df["EarningYield_TTM"] = ((stock_consolidate_df["EPS_TTM"] / stock_consolidate_df["stock_price"]) * 100).round(2)
    stock_consolidate_df["ERP_TTM"] = stock_consolidate_df["EarningYield_TTM"] - US_T_10yrs_YTM # it means a comparison between equity return and 10 years risk free, usually ERP >= 3 for short term invest at least, ERP >= 5 for long term invest 

    # stock_consolidate_df['latest_qtr_liquidation_mktcap_ratio_%'] = stock_ratios_qtr_consolidate_df['liquidation_mktcap_ratio_%'].values[-1]
    stock_consolidate_df['BVPS_latest'] = qtr_balancesheet_df['BVPS_latest'].values[-1]

    stock_consolidate_df['MA200_slope'] = Daily_stock_df['MA200_slope']

    stock_consolidate_df['FCF_per_share_TTM'] = round((qtr_cashflow_df['operatingCashflow'] - qtr_cashflow_df['capitalExpenditures']).tail(4).sum() / qtr_balancesheet_df['commonStockSharesOutstanding'].values[-1], 2)
    stock_consolidate_df['PFCF_TTM'] = round(stock_consolidate_df['stock_price'][0]  / stock_consolidate_df['FCF_per_share_TTM'], 2)
    stock_consolidate_df['FCF_yield_TTM'] = round((stock_consolidate_df['FCF_per_share_TTM'] / stock_consolidate_df['stock_price'][0]) * 100, 2) # % return on cash of every single dollar you spent on stock price, the higher the better

    # EPS trend for next year estimates
    stock_consolidate_df['next_yr_days7ago_EPS'] = round(next_yr_days7ago_EPS, 2)
    stock_consolidate_df['next_yr_days30ago_EPS'] = round(next_yr_days30ago_EPS, 2)
    stock_consolidate_df['next_yr_days60ago_EPS'] = round(next_yr_days60ago_EPS, 2)
    stock_consolidate_df['next_yr_days90ago_EPS'] = round(next_yr_days90ago_EPS, 2)

    # symbol growth rate
    stock_consolidate_df['curr_yr_growthrate_symbol'] = round(curr_yr_growthrate_symbol, 2)
    stock_consolidate_df['next_yr_growthrate_symbol'] = round(next_yr_growthrate_symbol, 2)
    stock_consolidate_df['curr_yr_growthrate_index'] = round(curr_yr_growthrate_index, 2)
    stock_consolidate_df['next_yr_growthrate_index'] = round(next_yr_growthrate_index, 2)

    # filter conditions
    conditions = [
    (stock_consolidate_df["stock_price"] < stock_consolidate_df["relative_valuation_TTM_-"]),
    (stock_consolidate_df["stock_price"] > stock_consolidate_df["relative_valuation_TTM_+"]),
    ((stock_consolidate_df["stock_price"] >= stock_consolidate_df["relative_valuation_TTM_-"]) & (stock_consolidate_df["stock_price"] <= stock_consolidate_df["relative_valuation_TTM_+"])),
    ]

    categories = [
        'undervalued'
        ,'overvalued'
        ,'fair'
        ]

    # This KPI assess if the current stock price is under/over/fair to the current relative valuation
    stock_consolidate_df["curr_assessment"] = None

    for condition, category in zip(conditions, categories):
        stock_consolidate_df.loc[condition, "price_valuation_assessment"] = category





    # Append key-value pairs to the dictionary
    selected_cols = [
    "Ticker"
    ,"stock_price"
    ,"EPS_currentQtr"
    ,"EPS_nextQtr"
    ,"EPS_TTM"
    ,"EPS_nextQtr_TTM"
    ,"EPS_nextYr"
    # ,"PE_1yr_forward"
    ,"PE_TTM"
    ,"PE_TTM_avg"
    ,"PE_TTM_volatility_+"
    ,"PE_TTM_volatility_-"
    ,f"PE_{PE_yr_range-1}yr_avg"
    ,f"PE_{PE_yr_range-1}yr_volatility_+"
    ,f"PE_{PE_yr_range-1}yr_volatility_-"
    ,"relative_valuation_TTM_+"
    ,"relative_valuation_TTM_-"
    ,"relative_valuation_TTM_median"
    ,"relative_valuation_nextQuater_projected_+"
    ,"relative_valuation_nextQuater_projected_-"
    ,"relative_valuation_nextQuater_projected_median"
    ,"relative_valuation_nextYear_projected_+"
    ,"relative_valuation_nextYear_projected_-"
    ,"relative_valuation_nextYear_projected_median"
    ,"price_valuation_assessment"
    ,"EPS_nextQtr_growthRate"
    ,"EPS_nextYr_growthRate"
    # ,"PEG_next12months"
    # ,"PEG_TTM"
    ,"EarningYield_TTM"
    ,"ERP_TTM"
    # ,"latest_qtr_liquidation_mktcap_ratio_%"
    ,"BVPS_latest"
    ,"PFCF_TTM"
    ,"FCF_yield_TTM" 
    # ,"MA200_slope"
    ,'next_yr_days7ago_EPS'
    ,'next_yr_days30ago_EPS'
    ,'next_yr_days60ago_EPS'
    ,'next_yr_days90ago_EPS'
    ,'curr_yr_growthrate_symbol'
    ,'next_yr_growthrate_symbol'
    ,'curr_yr_growthrate_index'
    ,'next_yr_growthrate_index'
    ]


    # store each stock info as pd into dictionary
    ticker_dict_pd[symbol] = stock_consolidate_df[selected_cols]
    # transfer pandas dataframe to json format, and each stock info into dictionary
    ticker_dict_json[symbol] = stock_consolidate_df[selected_cols].to_dict()

    if j == 0:
        # screener df creation
        # screener df will store each stock's consolidate df's first row and union them together for screening purposee
        ticker_screen_df = pd.DataFrame(
            columns=selected_cols
        ) 
        stock_consolidate_df_values = stock_consolidate_df[selected_cols].values[0]

        # Insert rows into the DataFrame
        ticker_screen_df.loc[j] = stock_consolidate_df_values

    else:
        stock_consolidate_df_values = stock_consolidate_df[selected_cols].values[0]

        
        ticker_screen_df.loc[j] = stock_consolidate_df_values

# ticker screen df consolidated metrics
ticker_screen_df['Industry_PE_TTM_avg'] = round(ticker_screen_df['PE_TTM'].mean(), 2)

0 MO
1 ADM
2 BG
3 CPB
4 CHD
5 CLX
6 KO
7 CL
8 CAG
9 STZ
10 COST
11 DG
12 DLTR
13 EL
14 GIS
15 HSY
16 HRL
17 KDP
18 KMB
19 KHC
20 KR
21 LW
22 MKC
23 TAP
24 MDLZ
25 MNST
26 PEP
27 PM
28 PG
29 SJM
30 SYY
31 TGT
32 TSN
33 WMT

In [12]:
ticker_dict_pd['CL']

,Ticker,stock_price,EPS_currentQtr,EPS_nextQtr,EPS_TTM,EPS_nextQtr_TTM,EPS_nextYr,PE_TTM,PE_TTM_avg,PE_TTM_volatility_+,PE_TTM_volatility_-,PE_8yr_avg,PE_8yr_volatility_+,PE_8yr_volatility_-,relative_valuation_TTM_+,relative_valuation_TTM_-,relative_valuation_TTM_median,relative_valuation_nextQuater_projected_+,relative_valuation_nextQuater_projected_-,relative_valuation_nextQuater_projected_median,relative_valuation_nextYear_projected_+,relative_valuation_nextYear_projected_-,relative_valuation_nextYear_projected_median,price_valuation_assessment,EPS_nextQtr_growthRate,EPS_nextYr_growthRate,EarningYield_TTM,ERP_TTM,BVPS_latest,PFCF_TTM,FCF_yield_TTM,next_yr_days7ago_EPS,next_yr_days30ago_EPS,next_yr_days60ago_EPS,next_yr_days90ago_EPS,curr_yr_growthrate_symbol,next_yr_growthrate_symbol,curr_yr_growthrate_index,next_yr_growthrate_index
2026-03-05,CL,92.67,0.95,0.96783,3.69,3.74783,4.15,25.11,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.98,-0.11,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-03-04,CL,95.28,0.95,0.96783,3.69,3.74783,4.15,25.82,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.87,-0.22,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-03-03,CL,95.51,0.95,0.96783,3.69,3.74783,4.15,25.88,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.86,-0.23,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-03-02,CL,97.30,0.95,0.96783,3.69,3.74783,4.15,26.37,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.79,-0.30,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-27,CL,99.14,0.95,0.96783,3.69,3.74783,4.15,26.87,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.72,-0.37,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-26,CL,97.55,0.95,0.96783,3.69,3.74783,4.15,26.44,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.78,-0.31,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-25,CL,96.67,0.95,0.96783,3.69,3.74783,4.15,26.20,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.82,-0.27,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-24,CL,98.11,0.95,0.96783,3.69,3.74783,4.15,26.59,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.76,-0.33,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-23,CL,97.10,0.95,0.96783,3.69,3.74783,4.15,26.31,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.80,-0.29,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-20,CL,95.09,0.95,0.96783,3.69,3.74783,4.15,25.77,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.88,-0.21,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-19,CL,93.98,0.95,0.96783,3.69,3.74783,4.15,25.47,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.93,-0.16,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-18,CL,95.58,0.95,0.96783,3.69,3.74783,4.15,25.90,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.86,-0.23,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-17,CL,95.65,0.95,0.96783,3.69,3.74783,4.15,25.92,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.86,-0.23,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-13,CL,96.67,0.95,0.96783,3.69,3.74783,4.15,26.20,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.82,-0.27,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-12,CL,96.17,0.95,0.96783,3.69,3.74783,4.15,26.06,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.84,-0.25,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-11,CL,95.31,0.95,0.96783,3.69,3.74783,4.15,25.83,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.87,-0.22,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-10,CL,93.93,0.95,0.96783,3.69,3.74783,4.15,25.46,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.93,-0.16,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-09,CL,94.16,0.95,0.96783,3.69,3.74783,4.15,25.52,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.92,-0.17,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-06,CL,94.41,0.95,0.96783,3.69,3.74783,4.15,25.59,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.91,-0.18,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-05,CL,94.88,0.95,0.96783,3.69,3.74783,4.15,25.71,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.89,-0.20,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-04,CL,94.37,0.95,0.96783,3.69,3.74783,4.15,25.57,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.91,-0.18,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-03,CL,93.15,0.95,0.96783,3.69,3.74783,4.15,25.24,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,3.96,-0.13,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-02-02,CL,91.89,0.95,0.96783,3.69,3.74783,4.15,24.90,22.89,24.79,20.99,24.81,27.25,22.37,91.48,77.45,84.46,92.91,78.67,85.79,102.82,87.06,94.94,overvalued,1.57,12.41,4.02,-0.07,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-30,CL,90.29,0.91,0.96783,3.65,3.74783,4.15,24.74,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.04,-0.05,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-29,CL,85.24,0.91,0.96783,3.65,3.74783,4.15,23.35,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.28,0.19,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-28,CL,85.00,0.91,0.96783,3.65,3.74783,4.15,23.29,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.29,0.20,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-27,CL,85.76,0.91,0.96783,3.65,3.74783,4.15,23.50,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.26,0.17,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-26,CL,85.20,0.91,0.96783,3.65,3.74783,4.15,23.34,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.28,0.19,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-23,CL,86.66,0.91,0.96783,3.65,3.74783,4.15,23.74,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.21,0.12,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-22,CL,85.81,0.91,0.96783,3.65,3.74783,4.15,23.51,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.25,0.16,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-21,CL,84.73,0.91,0.96783,3.65,3.74783,4.15,23.21,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.31,0.22,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-20,CL,85.44,0.91,0.96783,3.65,3.74783,4.15,23.41,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.27,0.18,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-16,CL,84.52,0.91,0.96783,3.65,3.74783,4.15,23.16,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.32,0.23,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-15,CL,84.34,0.91,0.96783,3.65,3.74783,4.15,23.11,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.33,0.24,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-14,CL,84.55,0.91,0.96783,3.65,3.74783,4.15,23.16,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.32,0.23,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-13,CL,82.96,0.91,0.96783,3.65,3.74783,4.15,22.73,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.40,0.31,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-12,CL,81.93,0.91,0.96783,3.65,3.74783,4.15,22.45,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.46,0.37,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-09,CL,81.48,0.91,0.96783,3.65,3.74783,4.15,22.32,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.48,0.39,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-08,CL,80.87,0.91,0.96783,3.65,3.74783,4.15,22.16,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.51,0.42,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-07,CL,77.09,0.91,0.96783,3.65,3.74783,4.15,21.12,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.73,0.64,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-06,CL,77.20,0.91,0.96783,3.65,3.74783,4.15,21.15,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.73,0.64,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-05,CL,76.93,0.91,0.96783,3.65,3.74783,4.15,21.08,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.74,0.65,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2026-01-02,CL,77.69,0.91,0.96783,3.65,3.74783,4.15,21.28,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.70,0.61,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-31,CL,79.02,0.91,0.96783,3.65,3.74783,4.15,21.65,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.62,0.53,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-30,CL,79.51,0.91,0.96783,3.65,3.74783,4.15,21.78,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.59,0.50,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-29,CL,79.69,0.91,0.96783,3.65,3.74783,4.15,21.83,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.58,0.49,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-26,CL,79.73,0.91,0.96783,3.65,3.74783,4.15,21.84,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.58,0.49,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-24,CL,80.25,0.91,0.96783,3.65,3.74783,4.15,21.99,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.55,0.46,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-23,CL,79.93,0.91,0.96783,3.65,3.74783,4.15,21.90,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.57,0.48,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-22,CL,79.04,0.91,0.96783,3.65,3.74783,4.15,21.65,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.62,0.53,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-19,CL,78.36,0.91,0.96783,3.65,3.74783,4.15,21.47,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.66,0.57,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-18,CL,77.73,0.91,0.96783,3.65,3.74783,4.15,21.30,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.70,0.61,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-17,CL,79.73,0.91,0.96783,3.65,3.74783,4.15,21.84,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.58,0.49,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-16,CL,78.95,0.91,0.96783,3.65,3.74783,4.15,21.63,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.62,0.53,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-15,CL,79.43,0.91,0.96783,3.65,3.74783,4.15,21.76,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.60,0.51,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-12,CL,78.34,0.91,0.96783,3.65,3.74783,4.15,21.46,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.66,0.57,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-11,CL,77.25,0.91,0.96783,3.65,3.74783,4.15,21.16,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.72,0.63,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-10,CL,77.76,0.91,0.96783,3.65,3.74783,4.15,21.30,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.69,0.60,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-09,CL,76.98,0.91,0.96783,3.65,3.74783,4.15,21.09,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.74,0.65,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-08,CL,76.11,0.91,0.96783,3.65,3.74783,4.15,20.85,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,undervalued,2.68,13.64,4.80,0.71,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-05,CL,78.07,0.91,0.96783,3.65,3.74783,4.15,21.39,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.68,0.59,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-04,CL,77.60,0.91,0.96783,3.65,3.74783,4.15,21.26,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.70,0.61,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-03,CL,78.20,0.91,0.96783,3.65,3.74783,4.15,21.42,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.67,0.58,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-02,CL,78.82,0.91,0.96783,3.65,3.74783,4.15,21.59,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.63,0.54,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-12-01,CL,79.94,0.91,0.96783,3.65,3.74783,4.15,21.90,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.57,0.48,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-28,CL,80.39,0.91,0.96783,3.65,3.74783,4.15,22.02,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.54,0.45,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-26,CL,80.04,0.91,0.96783,3.65,3.74783,4.15,21.93,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.56,0.47,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-25,CL,79.82,0.91,0.96783,3.65,3.74783,4.15,21.87,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.57,0.48,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-24,CL,79.18,0.91,0.96783,3.65,3.74783,4.15,21.69,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.61,0.52,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-21,CL,80.93,0.91,0.96783,3.65,3.74783,4.15,22.17,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.51,0.42,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-20,CL,78.86,0.91,0.96783,3.65,3.74783,4.15,21.61,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.63,0.54,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-19,CL,78.47,0.91,0.96783,3.65,3.74783,4.15,21.50,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.65,0.56,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-18,CL,79.33,0.91,0.96783,3.65,3.74783,4.15,21.73,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.60,0.51,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-17,CL,78.81,0.91,0.96783,3.65,3.74783,4.15,21.59,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.63,0.54,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-14,CL,78.05,0.91,0.96783,3.65,3.74783,4.15,21.38,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.68,0.59,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-13,CL,78.79,0.91,0.96783,3.65,3.74783,4.15,21.59,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.63,0.54,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-12,CL,78.56,0.91,0.96783,3.65,3.74783,4.15,21.52,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.65,0.56,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-11,CL,79.47,0.91,0.96783,3.65,3.74783,4.15,21.77,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.59,0.50,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-10,CL,78.47,0.91,0.96783,3.65,3.74783,4.15,21.50,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.65,0.56,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-07,CL,78.76,0.91,0.96783,3.65,3.74783,4.15,21.58,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.63,0.54,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-06,CL,77.27,0.91,0.96783,3.65,3.74783,4.15,21.17,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.72,0.63,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75
2025-11-05,CL,76.91,0.91,0.96783,3.65,3.74783,4.15,21.07,22.89,24.79,20.99,24.81,27.25,22.37,90.48,76.61,84.46,92.91,78.67,85.79,102.82,87.06,94.94,fair,2.68,13.64,4.75,0.66,0.07,20.5,4.88,4.14,4.13,4.1,4.11,5.17,6.88,13.39,15.75

# Stock screener

In [8]:
ticker_screen_df = ticker_screen_df.sort_values(by=['price_valuation_assessment']
                                                ,ascending=False)

selected_cols = [
    'Ticker'

    ,'BVPS_latest'
    ,'stock_price'
    # Earnings
    ,'EPS_TTM'
    ,"EPS_nextYr"

    # PE relative valuation
    ,'PE_TTM'
    ,'PE_TTM_avg'
    ,f"PE_{PE_yr_range-1}yr_avg"
    ,f"PE_{PE_yr_range-1}yr_volatility_+"
    ,f"PE_{PE_yr_range-1}yr_volatility_-"
    ,"relative_valuation_TTM_+"
    ,"relative_valuation_TTM_-"
    ,"relative_valuation_TTM_median"
    ,"relative_valuation_nextQuater_projected_+"
    ,"relative_valuation_nextQuater_projected_-"
    ,"relative_valuation_nextQuater_projected_median"
    ,"relative_valuation_nextYear_projected_+"
    ,"relative_valuation_nextYear_projected_-"
    ,"relative_valuation_nextYear_projected_median"
    ,'price_valuation_assessment'

    # Growth
    ,"EPS_nextQtr_growthRate"
    ,"EPS_nextYr_growthRate"
    # ,"PEG_next12months"
    # ,"PEG_TTM"

    # Other valuation metrics
    ,'ERP_TTM'
    # ,'latest_qtr_liquidation_mktcap_ratio_%'
    ,'PFCF_TTM'
    ,'FCF_yield_TTM'
    ,'next_yr_days7ago_EPS'
    ,'next_yr_days30ago_EPS'
    ,'next_yr_days60ago_EPS'
    ,'next_yr_days90ago_EPS'
    ,'curr_yr_growthrate_symbol'
    ,'next_yr_growthrate_symbol'
    ,'curr_yr_growthrate_index'
    ,'next_yr_growthrate_index'
    ,'Industry_PE_TTM_avg'
]

ticker_screen_df[selected_cols]

,Ticker,BVPS_latest,stock_price,EPS_TTM,EPS_nextYr,PE_TTM,PE_TTM_avg,PE_8yr_avg,PE_8yr_volatility_+,PE_8yr_volatility_-,relative_valuation_TTM_+,relative_valuation_TTM_-,relative_valuation_TTM_median,relative_valuation_nextQuater_projected_+,relative_valuation_nextQuater_projected_-,relative_valuation_nextQuater_projected_median,relative_valuation_nextYear_projected_+,relative_valuation_nextYear_projected_-,relative_valuation_nextYear_projected_median,price_valuation_assessment,EPS_nextQtr_growthRate,EPS_nextYr_growthRate,ERP_TTM,PFCF_TTM,FCF_yield_TTM,next_yr_days7ago_EPS,next_yr_days30ago_EPS,next_yr_days60ago_EPS,next_yr_days90ago_EPS,curr_yr_growthrate_symbol,next_yr_growthrate_symbol,curr_yr_growthrate_index,next_yr_growthrate_index,Industry_PE_TTM_avg
25,MNST,8.36,75.61,1.96,2.57,38.58,43.08,24.59,33.82,15.36,89.08,79.79,84.44,95.07,85.16,90.12,116.7,104.53,110.62,undervalued,6.73,31.0,-1.54,37.99,2.63,2.58,2.57,2.51,2.51,13.81,12.97,14.94,15.75,21.12
3,CPB,13.23,25.8,2.86,2.57,9.02,9.83,14.94,18.09,11.79,29.43,26.8,28.12,27.82,25.33,26.58,26.47,24.1,25.28,undervalued,-5.48,-10.05,6.96,11.22,8.91,2.58,2.58,2.63,2.66,-18.48,6.25,14.94,15.75,21.12
13,EL,17.0,92.72,1.95,3.03,47.55,60.16,44.65,59.25,30.05,129.71,104.91,117.31,110.72,89.55,100.14,201.6,163.05,182.32,undervalued,-14.64,55.42,-2.03,16.62,6.02,3.01,2.94,2.93,2.94,47.42,36.14,14.94,15.75,21.12
0,MO,-2.09,66.51,5.42,5.81,12.27,11.28,11.49,15.08,7.9,65.15,57.13,61.14,68.05,59.67,63.86,69.82,61.22,65.52,overvalued,4.45,7.17,4.02,12.29,8.13,5.8,5.8,5.79,5.79,3.66,3.39,14.94,15.75,21.12
2,BG,89.07,116.67,7.38,9.91,15.81,13.79,10.71,20.53,0.89,113.95,89.59,101.77,110.8,87.12,98.96,153.08,120.36,136.72,overvalued,-2.76,34.34,2.2,-20.01,-5.0,9.94,10.35,9.92,10.0,7.25,22.12,14.94,15.75,21.12
4,CHD,16.7,100.7,3.52,4.04,28.61,26.09,28.79,31.57,26.01,98.45,85.22,91.84,100.31,86.83,93.57,113.03,97.84,105.44,overvalued,1.89,14.81,-0.63,22.08,4.53,4.04,4.03,3.98,3.99,6.79,7.2,14.94,15.75,21.12
20,KR,10.75,74.11,4.86,5.64,15.25,13.83,13.11,14.14,12.08,70.28,64.15,67.22,65.12,59.44,62.28,81.6,74.49,78.04,overvalued,-7.34,16.11,2.43,21.61,4.63,5.58,5.6,5.61,5.61,8.22,7.51,14.94,15.75,21.12
31,TGT,34.91,120.79,7.57,8.49,15.96,13.47,18.19,24.39,11.99,112.41,91.52,101.96,126.45,102.95,114.7,126.1,102.67,114.38,overvalued,12.49,12.18,2.14,19.08,5.24,8.12,8.17,8.15,8.18,5.41,6.42,14.94,15.75,21.12
7,CL,0.07,93.56,3.69,4.15,25.36,22.94,24.81,27.25,22.37,91.7,77.6,84.65,93.14,78.82,85.98,103.09,87.24,95.16,overvalued,1.57,12.42,-0.19,20.7,4.83,4.14,4.15,4.1,4.11,5.17,6.89,14.94,15.75,21.12
8,CAG,16.9,19.02,1.91,1.81,9.96,8.88,13.32,17.08,9.56,18.53,15.39,16.96,18.17,15.1,16.64,17.52,14.56,16.04,overvalued,-1.93,-5.42,5.91,10.39,9.62,1.8,1.81,1.82,1.86,-25.07,4.82,14.94,15.75,21.12
30,SYY,4.75,85.23,4.58,5.07,18.61,17.35,26.4,37.94,14.86,85.1,73.83,79.46,95.44,82.8,89.12,94.27,81.79,88.03,overvalued,12.15,10.78,1.24,21.25,4.7,5.07,5.1,5.05,5.05,2.92,10.53,14.94,15.75,21.12
29,SJM,49.07,111.21,8.69,7.99,12.8,11.51,13.46,15.89,11.03,105.5,94.55,100.02,104.36,93.53,98.94,96.98,86.91,91.94,overvalued,-1.08,-8.07,3.68,12.22,8.18,7.97,8.04,8.0,7.78,-10.69,10.99,14.94,15.75,21.12
19,KHC,35.1,24.54,2.59,2.15,9.47,8.88,12.91,16.39,9.43,23.8,22.2,23.0,23.02,21.47,22.24,19.73,18.4,19.06,overvalued,-3.29,-17.11,6.42,7.97,12.55,2.17,2.59,2.63,2.63,-21.72,5.47,14.94,15.75,21.12
1,ADM,46.97,67.44,3.42,4.66,19.72,17.24,13.61,16.19,11.03,64.84,53.08,58.96,69.62,56.99,63.31,88.37,72.34,80.36,overvalued,7.37,36.28,0.94,7.76,12.89,4.65,4.69,4.66,4.82,16.77,16.37,14.94,15.75,21.12
15,HSY,17.17,224.99,5.32,9.79,42.29,32.18,24.45,29.0,19.9,203.06,139.33,171.2,223.04,153.04,188.04,373.75,256.45,315.1,overvalued,9.84,84.05,-1.77,83.64,1.2,9.73,8.4,8.11,7.96,32.49,17.12,14.94,15.75,21.12
24,MDLZ,52.28,58.4,2.92,3.39,20.0,19.77,20.47,22.84,18.1,59.92,55.54,57.73,58.89,54.58,56.74,69.6,64.51,67.06,fair,-1.72,16.16,0.87,3.53,28.3,3.4,3.44,3.44,3.44,4.28,11.4,14.94,15.75,21.12
28,PG,22.0,153.63,6.79,7.33,22.63,21.81,25.14,27.65,22.63,155.9,140.28,148.09,155.65,140.06,147.86,168.31,151.45,159.88,fair,-0.16,7.96,0.29,25.06,3.99,7.33,7.32,7.35,7.39,2.01,5.22,14.94,15.75,21.12
26,PEP,14.88,159.43,8.15,9.13,19.56,19.07,23.0,26.57,19.43,162.67,148.17,155.42,178.39,162.48,170.44,182.27,166.02,174.14,fair,9.66,12.05,0.98,21.2,4.72,9.13,9.01,8.97,8.97,5.94,5.9,14.94,15.75,21.12
27,PM,-6.64,169.98,7.54,9.19,22.54,22.21,17.31,20.08,14.54,180.06,154.87,167.46,191.06,164.34,177.7,219.36,188.68,204.02,fair,6.11,21.83,0.31,23.97,4.17,9.19,9.09,9.11,9.13,11.71,9.06,14.94,15.75,21.12
22,MKC,21.3,64.85,3.0,3.36,21.62,22.46,28.42,32.29,24.55,69.93,64.83,67.38,72.71,67.4,70.06,78.36,72.65,75.5,fair,3.97,12.06,0.5,24.66,4.06,3.36,3.34,3.54,3.47,3.32,8.45,14.94,15.75,21.12
32,TSN,52.24,61.43,3.95,4.42,15.55,14.59,15.84,25.22,6.46,62.13,53.13,57.63,63.48,54.28,58.88,69.52,59.44,64.48,fair,2.17,11.89,2.3,19.14,5.23,4.44,4.38,4.34,4.5,-5.74,13.81,14.94,15.75,21.12
23,TAP,52.28,46.64,5.43,5.04,8.59,8.77,11.61,13.22,10.0,49.68,45.56,47.62,61.45,56.35,58.9,46.16,42.32,44.24,fair,23.68,-7.1,7.51,8.54,11.71,5.16,5.73,5.78,5.78,-12.54,6.42,14.94,15.75,21.12
17,KDP,18.72,28.25,2.05,2.51,13.78,13.84,18.99,23.75,14.23,29.4,27.35,28.38,31.53,29.33,30.43,35.97,33.47,34.72,fair,7.26,22.38,3.13,25.68,3.89,2.31,2.31,2.31,2.32,8.92,12.35,14.94,15.75,21.12
21,LW,12.57,46.03,3.4,3.01,13.54,15.19,25.69,34.44,16.94,59.57,43.72,51.64,51.7,37.95,44.82,52.82,38.77,45.8,fair,-13.21,-11.34,3.26,9.88,10.12,3.01,3.03,3.04,3.51,-17.99,9.73,14.94,15.75,21.12
18,KMB,4.51,104.58,7.3,7.71,14.33,15.05,19.1,22.02,16.18,115.7,104.02,109.86,121.9,109.6,115.75,122.24,109.9,116.07,fair,5.36,5.65,2.85,22.06,4.53,7.71,7.72,7.89,7.9,0.71,1.7,14.94,15.75,21.12
16,HRL,17.17,24.42,1.36,1.58,17.96,16.95,23.44,27.02,19.86,24.71,21.39,23.05,25.16,21.79,23.48,28.75,24.89,26.82,fair,1.83,16.33,1.44,23.04,4.34,1.56,1.56,1.56,1.53,7.7,7.22,14.94,15.75,21.12
14,GIS,17.17,44.29,4.74,3.48,9.34,9.27,16.04,19.07,13.01,46.4,41.48,43.94,44.13,39.44,41.78,34.08,30.46,32.27,fair,-4.9,-26.56,6.57,13.46,7.43,3.48,3.73,3.74,3.79,-16.75,-0.68,14.94,15.75,21.12
12,DLTR,17.0,115.79,5.35,6.74,21.64,22.46,21.27,25.74,16.8,131.18,109.14,120.16,117.51,97.77,107.64,165.19,137.43,151.31,fair,-10.42,25.92,0.49,16.85,5.93,6.73,6.71,6.69,6.4,4.39,17.12,14.94,15.75,21.12
11,DG,37.05,146.31,6.6,7.18,22.17,20.21,21.44,27.54,15.34,150.61,116.16,133.38,157.17,121.22,139.2,163.9,126.41,145.16,fair,4.36,8.82,0.38,13.82,7.24,7.16,7.15,7.07,6.68,10.31,10.2,14.94,15.75,21.12
10,COST,72.18,998.1,19.23,22.76,51.9,49.67,47.97,59.24,36.7,1001.31,909.0,955.16,1113.82,1011.15,1062.48,1185.26,1076.0,1130.63,fair,11.24,18.37,-2.2,48.76,2.05,22.33,22.27,22.25,22.14,12.79,10.56,14.94,15.75,21.12
9,STZ,44.16,146.47,12.54,12.36,11.68,11.52,21.75,27.78,15.72,157.13,131.8,144.46,166.12,139.34,152.73,154.87,129.91,142.39,fair,5.72,-1.43,4.43,14.52,6.89,12.36,12.36,12.39,12.43,-15.77,6.49,14.94,15.75,21.12
6,KO,7.46,77.04,3.0,3.47,25.68,24.48,24.32,26.38,22.26,77.13,69.75,73.44,82.63,74.73,78.68,89.1,80.57,84.84,fair,7.13,15.52,-0.24,62.63,1.6,3.46,3.46,3.46,3.46,7.84,7.12,14.94,15.75,21.12
5,CLX,16.7,114.66,6.56,6.82,17.48,16.32,25.62,31.0,20.24,116.96,97.15,107.06,128.36,106.62,117.49,121.53,100.94,111.24,fair,9.74,3.9,1.59,35.28,2.83,6.82,6.74,6.76,6.77,-23.27,15.06,14.94,15.75,21.12
33,WMT,12.44,123.8,2.65,3.29,46.72,44.83,22.82,32.44,13.2,127.17,110.43,118.8,133.79,116.17,124.98,157.95,137.15,147.55,fair,5.2,24.2,-1.99,66.56,1.5,3.29,3.32,3.31,3.31,10.81,12.51,14.94,15.75,21.12

# Price EPS chart

In [10]:
# Parameters section
alpha_vantage_api_key = API_KEY


ticker_symbols = [
    'EIX'
]

In [11]:
# Daily quote section
for j, symbol in enumerate(ticker_symbols):

    print(j, symbol)
    # STOCK SPLIT FACTOR section
    url = f'https://www.alphavantage.co/query?function=SPLITS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'data':
            if len(value) > 0:
                stock_split_record_df = pd.DataFrame(value)
                stock_split_record_df['split_factor'] = pd.to_numeric(stock_split_record_df['split_factor'], errors='coerce') # change split_factor series to numeric data
                stock_split_record_df['effective_date'] = pd.to_datetime(stock_split_record_df['effective_date'])
            else:
                # Use pandas index assign instead of direct assign value
                stock_split_record_df = pd.DataFrame({
                'split_factor': [1],
                'effective_date': [datetime.today()]
            })


    # Daily quote section
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={symbol}&apikey={alpha_vantage_api_key}&outputsize=full'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'Time Series (Daily)':


            selected_cols = [
                '4. close'
            ]

            Daily_stock_df = pd.DataFrame(value).transpose()[selected_cols] # tranpose the dataframe and sub select selected cols

            # Rename columns
            Daily_stock_df.rename(
                columns={
                    '4. close': 'stock_price'
                    }
                ,inplace=True
                )
            
            Daily_stock_df["stock_price"] = Daily_stock_df["stock_price"].astype(str).apply(lambda x: float(x))
            Daily_stock_df["stock_price"] = Daily_stock_df["stock_price"].round(2)
            Daily_stock_df.index = pd.to_datetime(Daily_stock_df.index)


    for date_i in Daily_stock_df.index.date:
        for date_j in stock_split_record_df['effective_date'].dt.date:
            if date_i == date_j:

                # stock price to divided the split factor
                Daily_stock_df.loc[Daily_stock_df.index.date < date_j, 'stock_price'] /= (stock_split_record_df['split_factor'][stock_split_record_df['effective_date'].dt.date == date_j].values[0])




    # Earning section
    # past earnings from alpha vintage API
    url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'annualEarnings':

            selected_cols = [
                'fiscalDateEnding'
                ,'reportedEPS'
            ]

            annualEPS_df = pd.DataFrame(value) # tranpose the dataframe and sub select selected cols


            annualEPS_df['fiscalDateEnding'] = pd.to_datetime(annualEPS_df['fiscalDateEnding']).dt.year


            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    annualEPS_df[f'{col}'] = annualEPS_df[f'{col}'].astype(str).apply(lambda x: float(x))

                else:
                    continue
            
            # clean annualEPS_df
            annualEPS_df = annualEPS_df.sort_values('reportedEPS', ascending=False).drop_duplicates('fiscalDateEnding')
            annualEPS_df = annualEPS_df.sort_values('fiscalDateEnding', ascending=False).reset_index(drop=True)



        if key == 'quarterlyEarnings':

            selected_cols = [
                'reportedDate'
                ,'reportedEPS'
            ]

            qtrEPS_df = pd.DataFrame(value)[selected_cols] # tranpose the dataframe and sub select selected cols
            qtrEPS_df['reportedDate'] = pd.to_datetime(qtrEPS_df['reportedDate'])

            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    qtrEPS_df[col] = qtrEPS_df[col].astype(str).apply(lambda x: float(x) if x not in [None, 'None', 'nan', 'NaN'] else float(0))
                else:
                    continue



    # Consolidated section
    stock_consolidate_df = Daily_stock_df
    stock_consolidate_df_date = stock_consolidate_df.index
    for i in stock_consolidate_df_date:
                
        # Filter the DataFrame to include only dates(index) less than or equal to the target date
        filtered_qtrEPS_df = qtrEPS_df[qtrEPS_df['reportedDate'] < i]

        # Select the first four rows from the past_qtrs_EPS
        past_4_qtrs_EPS = filtered_qtrEPS_df.head(4) 
        past_3_qtrs_EPS = filtered_qtrEPS_df.head(3)
        past_1_qtr_EPS = filtered_qtrEPS_df.head(1)

        # Calculate the sum of the numeric values in the selected rows
        EPS_TTM = past_4_qtrs_EPS['reportedEPS'].values.sum()
        EPS_curr_qtr = past_1_qtr_EPS['reportedEPS'].values.sum()

        # assign each index row with the EPS_TTM
        stock_consolidate_df.loc[i, "EPS_TTM"] = EPS_TTM
        stock_consolidate_df.loc[i, "EPS_currentQtr"] = EPS_curr_qtr


    # stock's stats
    stock_consolidate_df["Ticker"] = symbol
    stock_consolidate_df["PE_TTM"] = (stock_consolidate_df["stock_price"] / stock_consolidate_df["EPS_TTM"]).round(2)
    stock_consolidate_df["PE_TTM_avg"] = stock_consolidate_df["PE_TTM"].mean().round(2)
    stock_consolidate_df["PE_TTM_std"] = np.std(stock_consolidate_df["PE_TTM"]).round(2)
    stock_consolidate_df["PE_TTM_volatility_+"] = (stock_consolidate_df["PE_TTM_avg"] + stock_consolidate_df["PE_TTM_std"]).round(2) # 这个是PE的波动范围上限
    stock_consolidate_df["PE_TTM_volatility_-"] = (stock_consolidate_df["PE_TTM_avg"] - stock_consolidate_df["PE_TTM_std"]).round(2) # 这个是PE的波动范围下限

    stock_consolidate_df["relative_valuation_TTM_+"] = (stock_consolidate_df["PE_TTM_volatility_+"] * stock_consolidate_df["EPS_TTM"]).round(2) # 这个是relative valuation的价格上限
    stock_consolidate_df["relative_valuation_TTM_-"] = (stock_consolidate_df["PE_TTM_volatility_-"] * stock_consolidate_df["EPS_TTM"]).round(2) # 这个是relative valuation的价格下限
    stock_consolidate_df["relative_valuation_TTM_median"] = (np.median([stock_consolidate_df["relative_valuation_TTM_+"][0], stock_consolidate_df["relative_valuation_TTM_-"][0]])).round(2) #这个是根据最新TTM PE估值的价格中位数

0 EIX

In [12]:
import plotly.graph_objects as go


# Create the figure
fig = go.Figure()

# Add stock_price on primary y-axis (left)
fig.add_trace(go.Scatter(
    x=stock_consolidate_df.index,
    y=stock_consolidate_df["stock_price"],
    mode='lines',
    line=dict(color='black'),
    name='Stock Price',
    yaxis="y1"
))

# Add EPS_TTM on secondary y-axis (right)
fig.add_trace(go.Scatter(
    x=stock_consolidate_df.index,
    y=stock_consolidate_df["EPS_TTM"],
    mode='lines',
    fill='tonexty',  # Shadow effect
    line=dict(color='green'),
    name='EPS_TTM',
    yaxis="y2"
))

# Add PE_TTM on secondary y-axis (right)
fig.add_trace(go.Scatter(
    x=stock_consolidate_df.index,
    y=stock_consolidate_df["PE_TTM"],
    mode='lines',
    line=dict(color='blue', dash='dot'),
    name='PE_TTM',
    yaxis="y2"
))

# Update layout to remove grid and configure dual y-axes
fig.update_layout(
    title="Stock Metrics Over Time",
    xaxis=dict(title="Date", showgrid=False),
    yaxis=dict(
        title="Stock Price",
        showgrid=False,
        titlefont=dict(color="black"),
        tickfont=dict(color="black")
    ),
    yaxis2=dict(
        title="EPS_TTM & PE_TTM",
        overlaying="y",  # Overlay with y1
        side="right",
        showgrid=False,
        titlefont=dict(color="blue"),
        tickfont=dict(color="blue")
    ),
    legend_title="Metrics",
    template="plotly_white",
    plot_bgcolor='white'  # Background color
)

# Show the plot
fig.show()

# Financial statement of single stock

In [13]:
stock_financial_dict = {} # the dict will store ticker as key, the string value of 'annual_df' and 'qtr_df' as nested key, actual json as value

ticker_symbols = [
    'EIX'
    ]
# ticker_symbols = electric_utility_symbols
PE_yr_range = 15 # test for 'X' years PE 


# storage process
for j, symbol in enumerate(ticker_symbols):
    print(j, symbol)
    # # COMPANY OVERVIEW
    # # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    # url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey={alpha_vantage_api_key}'
    # r = requests.get(url)
    # data = r.json()

    
    # for key, value in data.items():
    #     if key  == 'MarketCapitalization':
    #         stock_mkt_cap = float(value)



    # STOCK SPLIT FACTOR section
    url = f'https://www.alphavantage.co/query?function=SPLITS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'data':
            if len(value) > 0:
                stock_split_record_df = pd.DataFrame(value)
                stock_split_record_df['split_factor'] = pd.to_numeric(stock_split_record_df['split_factor'], errors='coerce') # change split_factor series to numeric data
                stock_split_record_df['effective_date'] = pd.to_datetime(stock_split_record_df['effective_date'])
            else:
                # Use pandas index assign instead of direct assign value
                stock_split_record_df = pd.DataFrame({
                'split_factor': [1],
                'effective_date': [datetime.today()]
            })


    # Monthly quote section
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'Monthly Time Series':
            Monthly_stock_df = pd.DataFrame(value)


    Monthly_stock_df = Monthly_stock_df.transpose()
    Monthly_stock_df.index = pd.to_datetime(Monthly_stock_df.index)


    filter_1 = (Monthly_stock_df.index.year.isin(range((datetime.today().year - PE_yr_range) ,datetime.today().year)))
    filter_2 = (Monthly_stock_df.index.month == 12) # month = 12 to get the year end closing price

    selected_cols = [
        '4. close'
    ]

    Monthly_stock_df = Monthly_stock_df[
        filter_1
        & filter_2
    ][selected_cols]

    # Rename columns
    Monthly_stock_df.rename(
        columns={
            '4. close': 'stock_price'
            }
        ,inplace=True
        )

    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].astype(str).apply(lambda x: float(x))
    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].round(2)

    # modify stock price based on stock split
    for year_i in Monthly_stock_df.index.year:
        for year_j in stock_split_record_df['effective_date'].dt.year:
            if year_i == year_j:

                # stock price to divided the split factor
                Monthly_stock_df.loc[Monthly_stock_df.index.year < year_j, 'stock_price'] /= (stock_split_record_df['split_factor'][stock_split_record_df['effective_date'].dt.year == year_j].values[0])
    


    # Earning section
    # past earnings from alpha vintage API
    url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'annualEarnings':

            selected_cols = [
                'fiscalDateEnding'
                ,'reportedEPS'
            ]

            annualEPS_df = pd.DataFrame(value) # tranpose the dataframe and sub select selected cols


            annualEPS_df['fiscalDateEnding'] = pd.to_datetime(annualEPS_df['fiscalDateEnding']).dt.year

            annualEPS_df = annualEPS_df[
                annualEPS_df['fiscalDateEnding'].isin(
                    range(
                        (datetime.today().year - PE_yr_range) 
                        ,datetime.today().year
                            )
                            )
                            ]

            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    annualEPS_df[f'{col}'] = annualEPS_df[f'{col}'].astype(str).apply(lambda x: float(x))

                else:
                    continue
            # clean annualEPS_df
            annualEPS_df = annualEPS_df.sort_values('reportedEPS', ascending=False).drop_duplicates('fiscalDateEnding')
            annualEPS_df = annualEPS_df.sort_values('fiscalDateEnding', ascending=False).reset_index(drop=True)

            # calculate PE
            annualEPS_df["PE"] = Monthly_stock_df["stock_price"].values / annualEPS_df['reportedEPS'].values




    # INCOME STATEMENT
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=INCOME_STATEMENT&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()


    for key, value in data.items():
        if key == 'annualReports':
            annual_income_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_income_df = annual_income_df.sort_values('fiscalDateEnding', ascending=True)

            # annual measurements cols
            annual_income_metric_cols = annual_income_df.columns[1:]

            # Calculate quarter-over-quarter change percentage
            for column in annual_income_metric_cols:  # Exclude the 'fiscalDateEnding' column
                annual_income_df[column] = pd.to_numeric(annual_income_df[column], errors='coerce')
                annual_income_df[f'{column}_YoY'] = annual_income_df[column].pct_change() * 100 
            
            annual_income_YoY_metric_cols = [col for col in annual_income_df.columns if 'YoY' in col]

            # ratios of income statement calculation
            annual_income_df['gross_margin_%'] = (annual_income_df['grossProfit'] / annual_income_df['totalRevenue']) * 100
            annual_income_df['operating_margin_%'] = (annual_income_df['operatingIncome'] / annual_income_df['totalRevenue']) * 100
            annual_income_df['net_margin_%'] = (annual_income_df['netIncome'] / annual_income_df['totalRevenue']) * 100



        if key == 'quarterlyReports':
            qtr_income_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_income_df = qtr_income_df.sort_values('fiscalDateEnding', ascending=True)

            # qtr measurements cols
            qtr_income_metric_cols = qtr_income_df.columns[1:]
            
            # Calculate quarter-over-quarter change percentage
            for column in qtr_income_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_income_df[column] = pd.to_numeric(qtr_income_df[column], errors='coerce')
                qtr_income_df[f'{column}_QoQ'] = qtr_income_df[column].pct_change() * 100

            qtr_income_QoQ_metric_cols = [col for col in qtr_income_df.columns if 'QoQ' in col]

            # ratios of income statement calculation
            qtr_income_df['gross_margin_%'] = (qtr_income_df['grossProfit'] / qtr_income_df['totalRevenue']) * 100
            qtr_income_df['operating_margin_%'] = (qtr_income_df['operatingIncome'] / qtr_income_df['totalRevenue']) * 100
            qtr_income_df['net_margin_%'] = (qtr_income_df['netIncome'] / qtr_income_df['totalRevenue']) * 100

    income_ratio_cols = [
        'gross_margin_%'
        ,'operating_margin_%'
        ,'net_margin_%'
        ,'netIncome'
        ]
    
    
    # BALANCESHEET
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=BALANCE_SHEET&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():

        if key == 'annualReports':
            annual_balancesheet_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_balancesheet_df = annual_balancesheet_df.sort_values('fiscalDateEnding', ascending=True)

            for column in annual_balancesheet_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                annual_balancesheet_df[column] = pd.to_numeric(annual_balancesheet_df[column], errors='coerce')
                annual_balancesheet_df[f'{column}_YoY'] = annual_balancesheet_df[column].pct_change() * 100

            annual_balancesheet_df['current_ratio'] = (annual_balancesheet_df['totalCurrentAssets'] / annual_balancesheet_df['totalCurrentLiabilities'])
            annual_balancesheet_df['working_capital'] = annual_balancesheet_df['totalCurrentAssets'] - annual_balancesheet_df['totalCurrentLiabilities']
            annual_balancesheet_df['longTermDebt_to_workingCp_ratio'] = (annual_balancesheet_df['longTermDebt'] / annual_balancesheet_df['working_capital'])
            annual_balancesheet_df['debtEquity_ratio'] = (annual_balancesheet_df['totalLiabilities'] / annual_balancesheet_df['totalShareholderEquity'])
            annual_balancesheet_df['quick_ratio'] = ((annual_balancesheet_df['totalCurrentAssets'] - annual_balancesheet_df['inventory']) / annual_balancesheet_df['totalCurrentLiabilities'])

            
        if key == 'quarterlyReports':
            qtr_balancesheet_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_balancesheet_df = qtr_balancesheet_df.sort_values('fiscalDateEnding', ascending=True)

            for column in qtr_balancesheet_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_balancesheet_df[column] = pd.to_numeric(qtr_balancesheet_df[column], errors='coerce')
                qtr_balancesheet_df[f'{column}_YoY'] = qtr_balancesheet_df[column].pct_change() * 100

            qtr_balancesheet_df['current_ratio'] = (qtr_balancesheet_df['totalCurrentAssets'] / qtr_balancesheet_df['totalCurrentLiabilities'])
            qtr_balancesheet_df['working_capital'] = qtr_balancesheet_df['totalCurrentAssets'] - qtr_balancesheet_df['totalCurrentLiabilities']
            qtr_balancesheet_df['longTermDebt_to_workingCp_ratio'] = (qtr_balancesheet_df['longTermDebt'] / qtr_balancesheet_df['working_capital'])
            qtr_balancesheet_df['debtEquity_ratio'] = (qtr_balancesheet_df['totalLiabilities'] / qtr_balancesheet_df['totalShareholderEquity'])
            qtr_balancesheet_df['quick_ratio'] = ((qtr_balancesheet_df['totalCurrentAssets'] - qtr_balancesheet_df['inventory']) / qtr_balancesheet_df['totalCurrentLiabilities'])


    balancesheet_ratio_cols = [
        'current_ratio'
        ,'working_capital'
        ,'longTermDebt_to_workingCp_ratio'
        ,'debtEquity_ratio'
        ,'quick_ratio'
        ,'totalShareholderEquity'
    ]


    # CASHFLOW STATEMENT
    # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    url = f'https://www.alphavantage.co/query?function=CASH_FLOW&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():

        if key == 'annualReports':
            annual_cashflow_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            annual_cashflow_df = annual_cashflow_df.sort_values('fiscalDateEnding', ascending=True)

            for column in annual_cashflow_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                annual_cashflow_df[column] = pd.to_numeric(annual_cashflow_df[column], errors='coerce')
                annual_cashflow_df[f'{column}_YoY'] = annual_cashflow_df[column].pct_change() * 100

            
        if key == 'quarterlyReports':
            qtr_cashflow_df = pd.DataFrame(value).drop(['reportedCurrency'], axis=1)
            qtr_cashflow_df = qtr_cashflow_df.sort_values('fiscalDateEnding', ascending=True)

            for column in qtr_cashflow_df.columns[1:]:  # Exclude the 'fiscalDateEnding' column
                qtr_cashflow_df[column] = pd.to_numeric(qtr_cashflow_df[column], errors='coerce')
                qtr_cashflow_df[f'{column}_YoY'] = qtr_cashflow_df[column].pct_change() * 100



    cashflow_ratio_cols = [
        'operatingCashflow'
        ,'capitalExpenditures'
        ,'cashflowFromInvestment'
        ,'cashflowFromFinancing'
        ,'netIncome'
    ]


    ####################
    ### Consolidated ###
    ####################
    stock_ratios_annual_consolidate_df = pd.DataFrame()
    stock_ratios_qtr_consolidate_df = pd.DataFrame()
    stock_PE_annual_consolidate_df = pd.DataFrame()

    stock_ratios_annual_consolidate_df[income_ratio_cols] = annual_income_df[income_ratio_cols]
    stock_ratios_annual_consolidate_df[balancesheet_ratio_cols] = annual_balancesheet_df[balancesheet_ratio_cols]
    stock_ratios_annual_consolidate_df[cashflow_ratio_cols] = annual_cashflow_df[cashflow_ratio_cols]

    stock_ratios_qtr_consolidate_df[income_ratio_cols] = qtr_income_df[income_ratio_cols]
    stock_ratios_qtr_consolidate_df[balancesheet_ratio_cols] = qtr_balancesheet_df[balancesheet_ratio_cols]
    stock_ratios_qtr_consolidate_df[cashflow_ratio_cols] = qtr_cashflow_df[cashflow_ratio_cols]

    # calculating new consolidated metrics 
    # annual df
    stock_ratios_annual_consolidate_df['ROE_%'] = (annual_income_df['netIncome'] / annual_balancesheet_df['totalShareholderEquity']) * 100
    stock_ratios_annual_consolidate_df['liquidation_value'] = ((annual_balancesheet_df['totalAssets'] - annual_balancesheet_df['intangibleAssets']) - annual_balancesheet_df['totalLiabilities'])
    # stock_ratios_annual_consolidate_df['liquidation_mktcap_ratio_%'] = round((stock_ratios_annual_consolidate_df['liquidation_value'] / stock_mkt_cap) * 100, 2)
    stock_ratios_annual_consolidate_df['fiscalDateEnding'] = annual_balancesheet_df['fiscalDateEnding']

    stock_ratios_annual_consolidate_df['PE'] = annualEPS_df["PE"]
    stock_ratios_annual_consolidate_df['reportedEPS'] = annualEPS_df["reportedEPS"]

    # YoY %
    stock_ratios_annual_consolidate_df['QoQ_gross_margin_%_%'] = stock_ratios_annual_consolidate_df["gross_margin_%"].pct_change() * 100
    stock_ratios_annual_consolidate_df['QoQ_operating_margin_%_%'] = stock_ratios_annual_consolidate_df["operating_margin_%"].pct_change() * 100
    stock_ratios_annual_consolidate_df['QoQ_net_margin_%_%'] = stock_ratios_annual_consolidate_df["net_margin_%"].pct_change() * 100
    stock_ratios_annual_consolidate_df['YoY_reportedEPS_%'] = stock_ratios_annual_consolidate_df["reportedEPS"].pct_change() * 100 # yearly EPS 的增速



    # qtr df
    stock_ratios_qtr_consolidate_df['ROE_%'] = (qtr_income_df['netIncome'] / qtr_balancesheet_df['totalShareholderEquity']) * 100
    stock_ratios_qtr_consolidate_df['liquidation_value'] = ((qtr_balancesheet_df['totalAssets'] - qtr_balancesheet_df['intangibleAssets']) - qtr_balancesheet_df['totalLiabilities'])
    # stock_ratios_qtr_consolidate_df['liquidation_mktcap_ratio_%'] = round((stock_ratios_qtr_consolidate_df['liquidation_value'] / stock_mkt_cap) * 100, 2)
    stock_ratios_qtr_consolidate_df['fiscalDateEnding'] = qtr_balancesheet_df['fiscalDateEnding']
    
    # QoQ %
    stock_ratios_qtr_consolidate_df['QoQ_gross_margin_%_%'] = stock_ratios_qtr_consolidate_df["gross_margin_%"].pct_change() * 100
    stock_ratios_qtr_consolidate_df['QoQ_operating_margin_%_%'] = stock_ratios_qtr_consolidate_df["operating_margin_%"].pct_change() * 100
    stock_ratios_qtr_consolidate_df['QoQ_net_margin_%_%'] = stock_ratios_qtr_consolidate_df["net_margin_%"].pct_change() * 100




    # annual PE df
    if stock_PE_annual_consolidate_df.empty:
        stock_PE_annual_consolidate_df['fiscalDateEnding'] = annualEPS_df['fiscalDateEnding']

    stock_PE_annual_consolidate_df[f'{symbol}_PE'] = annualEPS_df["PE"].round(2)



    # reformat the columns order
    stock_ratios_annual_consolidate_df = stock_ratios_annual_consolidate_df[['fiscalDateEnding'] + [col for col in stock_ratios_annual_consolidate_df.columns if col != 'fiscalDateEnding']]
    stock_ratios_qtr_consolidate_df = stock_ratios_qtr_consolidate_df[['fiscalDateEnding'] + [col for col in stock_ratios_qtr_consolidate_df.columns if col != 'fiscalDateEnding']]




    # store the stock, dataframe value pair to the dictionary
    # transfer the pandas df to json
    stock_ratios_annual_consolidate_json = stock_ratios_annual_consolidate_df.to_dict()
    stock_ratios_qtr_consolidate_json = stock_ratios_qtr_consolidate_df.to_dict()

    stock_financial_dict[symbol] = {
    'annual': stock_ratios_annual_consolidate_json
    ,'qtr': stock_ratios_qtr_consolidate_json
    }

0 EIX

In [14]:
qtr_balancesheet_df.tail(10)

,fiscalDateEnding,totalAssets,totalCurrentAssets,cashAndCashEquivalentsAtCarryingValue,cashAndShortTermInvestments,inventory,currentNetReceivables,totalNonCurrentAssets,propertyPlantEquipment,accumulatedDepreciationAmortizationPPE,intangibleAssets,intangibleAssetsExcludingGoodwill,goodwill,investments,longTermInvestments,shortTermInvestments,otherCurrentAssets,otherNonCurrentAssets,totalLiabilities,totalCurrentLiabilities,currentAccountsPayable,deferredRevenue,currentDebt,shortTermDebt,totalNonCurrentLiabilities,capitalLeaseObligations,longTermDebt,currentLongTermDebt,longTermDebtNoncurrent,shortLongTermDebtTotal,otherCurrentLiabilities,otherNonCurrentLiabilities,totalShareholderEquity,treasuryStock,retainedEarnings,commonStock,commonStockSharesOutstanding,totalAssets_YoY,totalCurrentAssets_YoY,cashAndCashEquivalentsAtCarryingValue_YoY,cashAndShortTermInvestments_YoY,inventory_YoY,currentNetReceivables_YoY,totalNonCurrentAssets_YoY,propertyPlantEquipment_YoY,accumulatedDepreciationAmortizationPPE_YoY,intangibleAssets_YoY,intangibleAssetsExcludingGoodwill_YoY,goodwill_YoY,investments_YoY,longTermInvestments_YoY,shortTermInvestments_YoY,otherCurrentAssets_YoY,otherNonCurrentAssets_YoY,totalLiabilities_YoY,totalCurrentLiabilities_YoY,currentAccountsPayable_YoY,deferredRevenue_YoY,currentDebt_YoY,shortTermDebt_YoY,totalNonCurrentLiabilities_YoY,capitalLeaseObligations_YoY,longTermDebt_YoY,currentLongTermDebt_YoY,longTermDebtNoncurrent_YoY,shortLongTermDebtTotal_YoY,otherCurrentLiabilities_YoY,otherNonCurrentLiabilities_YoY,totalShareholderEquity_YoY,treasuryStock_YoY,retainedEarnings_YoY,commonStock_YoY,commonStockSharesOutstanding_YoY,current_ratio,working_capital,longTermDebt_to_workingCp_ratio,debtEquity_ratio,quick_ratio
9,2023-09-30,80164000000,7235000000,446000000,446000000,505000000,3292000000,72929000000,1.494000e+09,NaN,NaN,NaN,NaN,NaN,4.024000e+09,NaN,2992000000,NaN,62593000000,9027000000,2108000000,NaN,NaN,4123000000,53566000000,1.292000e+09,29532000000,3.944000e+09,NaN,34768000000,2621000000,4.747000e+09,15670000000,NaN,7399000000,6301000000,385000000,0.770575,-2.440669,128.717949,128.717949,-1.174168,33.117671,1.100714,-97.249936,NaN,NaN,NaN,NaN,NaN,-13.573883,0.000000,-29.383998,NaN,1.189841,2.265775,17.765363,NaN,NaN,-5.544101,1.010749,4.955321,0.346585,-2.617284,NaN,0.164213,4.881953,-79.885593,-0.778826,NaN,-2.038925,0.494418,0.000000,0.801484,-1792000000,-16.479911,3.994448,0.745541
8,2023-12-31,81758000000,6811000000,345000000,345000000,527000000,2758000000,74947000000,NaN,NaN,NaN,NaN,NaN,NaN,4.227000e+09,NaN,3181000000,NaN,63814000000,8598000000,1983000000,NaN,NaN,3894000000,55216000000,1.221000e+09,30316000000,3.774000e+09,NaN,35311000000,2544000000,4.626000e+09,15501000000,NaN,7499000000,6338000000,383924912,1.988424,-5.860401,-22.645740,-22.645740,4.356436,-16.221142,2.767075,0.000000,NaN,NaN,NaN,NaN,NaN,5.044732,0.000000,6.316845,NaN,1.950697,-4.752409,-5.929791,NaN,NaN,-5.554208,3.080312,-5.495356,2.654747,-4.310345,NaN,1.561781,-2.937810,-2.548978,-1.078494,NaN,1.351534,0.587208,-0.279244,0.792161,-1787000000,-16.964745,4.116767,0.730868
7,2024-03-31,83599000000,7878000000,992000000,992000000,519000000,2667000000,75721000000,NaN,NaN,NaN,NaN,NaN,NaN,4.350000e+09,-4.288000e+09,3700000000,NaN,65984000000,7907000000,1904000000,NaN,NaN,2990000000,58077000000,1.206000e+09,32576000000,2.871000e+09,NaN,36653000000,3013000000,4.852000e+09,15172000000,NaN,7166000000,6361000000,385000000,2.251767,15.665835,187.536232,187.536232,-1.518027,-3.299492,1.032730,0.000000,NaN,NaN,NaN,NaN,NaN,2.909865,-33084.615385,16.315624,NaN,3.400508,-8.036753,-3.983863,NaN,NaN,-23.215203,5.181469,-1.228501,7.454809,-23.926868,NaN,3.800515,18.435535,4.885430,-2.122444,NaN,-4.440592,0.362891,0.280026,0.996332,-29000000,-1123.310345,4.349064,0.930694
6,2024-06-30,84818000000,8512000000,465000000,465000000,534000000,3027000000,76306000000,NaN,NaN,NaN,NaN,NaN,NaN,4.363000e+09,NaN,4486000000,NaN,66950000000,8274000000,1892000000,NaN,NaN,3328000000,58676000000,1.201000e+09,33099000000,3.203000e+09,NaN,37503000000,3054000000,4.664000e+09,15424000000,NaN,7326000000,6461000000,388000000,1.458151,8.047728,-53.125000,-53.125000,2.890173,13.498313,0.772573,0.000000,NaN,NaN,NaN,NaN,NaN,0.298851,0.000000,21.243243,NaN,1.463991,4.641457,-0.630252,NaN,NaN,11.304348,1.031389,-0.414594,1.605476,11.563915,NaN,2.319046,1.360770,-3.874691,1.660954,NaN,2.232766,1.572080,0.779221,1.028765,238000000,139.071429,4.340638,0.964225
5,2024-09-30,84749000000,7444000000,200000000,200000000,533000000,3982000000,77305000000,1.386000e+09,NaN,NaN,NaN,NaN,NaN,4.474000e+09,6.700000e+07,2729000000,NaN,66642000000,8507000000,2185000000,NaN,NaN,3240000000,58135000000,1.180000e+09,32303000000,3.116000e+09,NaN,36599000000,3082000000,4.565000e+09,15663000000,NaN,7486000000,6538000000,390000000,-0.081351,-12.546992,-56.989247,-56.989247,-0.187266,31.549389,1.309202,-7.228916,NaN,NaN,NaN,NaN,NaN,2.544121,-101.562500,-39.166295,NaN,-0.460045,2.816050,15.486258,NaN,NaN,-2.644231,-0.922012,-1.748543,-2.404906,-2.716204,NaN,-2.410474,0.916830,-2.122642,1.549533,NaN,2.184002,1.191766,0.515464,0.875044,-1063000000,-30.388523,4.254740,0.812390
4,2024-12-31,85579000000,7155000000,193000000,193000000,538000000,3017000000,78424000000,1.387000e+09,NaN,NaN,NaN,NaN,NaN,4.343000e+09,NaN,3407000000,NaN,67839000000,8439000000,2000000000,NaN,NaN,3171000000,59400000000,1.180000e+09,33534000000,3.047000e+09,NaN,37761000000,3268000000,4.507000e+09,15565000000,NaN,7567000000,6353000000,388000000,0.979363,-3.882321,-3.500000,-3.500000,0.938086,-24.234053,1.447513,0.072150,NaN,NaN,NaN,NaN,NaN,-2.928029,0.000000,24.844265,NaN,1.796165,-0.799342,-8.466819,NaN,NaN,-2.129630,2.175970,0.000000,3.810792,-2.214377,NaN,3.174950,6.035042,-1.270537,-0.625678,NaN,1.082020,-2.829612,-0.512821,0.847849,-1284000000,-26.116822,4.358432,0.784098
3,2025-03-31,88420000000,7427000000,1318000000,1318000000,539000000,2669000000,80993000000,1.373000e+09,NaN,NaN,NaN,NaN,NaN,4.290000e+09,NaN,2901000000,NaN,69623000000,7769000000,2156000000,NaN,NaN,3127000000,61854000000,1.169000e+09,35387000000,3.004000e+09,NaN,39560000000,2486000000,4.332000e+09,16622000000,NaN,8662000000,6315000000,385000000,3.319740,3.801537,582.901554,582.901554,0.185874,-11.534637,3.275783,-1.009373,NaN,NaN,NaN,NaN,NaN,-1.220355,0.000000,-14.851776,NaN,2.629756,-7.939329,7.800000,NaN,NaN,-1.387575,4.131313,-0.932203,5.525735,-1.411224,NaN,4.764175,-23.929009,-3.882849,6.790877,NaN,14.470728,-0.598143,-0.773196,0.955979,-342000000,-103.470760,4.188605,0.886601
2,2025-06-30,88813000000,6950000000,140000000,140000000,523000000,2829000000,81863000000,1.358000e+09,NaN,NaN,NaN,NaN,NaN,4.387000e+09,NaN,3458000000,NaN,69952000000,7965000000,1962000000,NaN,NaN,3519000000,61987000000,1.156000e+09,34971000000,3.399000e+09,NaN,39526000000,2484000000,4.110000e+09,16686000000,NaN,8709000000,6330000000,385000000,0.444470,-6.422512,-89.377845,-89.377845,-2.968460,5.994755,1.074167,-1.092498,NaN,NaN,NaN,NaN,NaN,2.261072,0.000000,19.200276,NaN,0.472545,2.522847,-8.998145,NaN,NaN,12.535977,0.215022,-1.112062,-1.175573,13.149134,NaN,-0.085945,-0.080451,-5.124654,0.385032,NaN,0.542600,0.237530,0.000000,0.872567,-1015000000,-34.454187,4.192257,0.806905
1,2025-09-30,90489000000,7728000000,456000000,456000000,524000000,3443000000,82761000000,1.380000e+09,NaN,NaN,NaN,NaN,NaN,4.545000e+09,NaN,3305000000,NaN,71159000000,9419000000,2346000000,NaN,NaN,3898000000,61740000000,1.180000e+09,34479000000,3.778000e+09,NaN,39437000000,3175000000,4.122000e+09,17155000000,NaN,9165000000,6343000000,385000000,1.887111,11.194245,225.714286,225.714286,0.191205,21.703782,1.096955,1.620029,NaN,NaN,NaN,NaN,NaN,3.601550,0.000000,-4.424523,NaN,1.725469,18.254865,19.571865,NaN,NaN,10.770105,-0.398471,2.076125,-1.406880,11.150338,NaN,-0.225168,27.818035,0.291971,2.810740,NaN,5.235963,0.205371,0.000000,0.820469,-1691000000,-20.389710,4.148003,0.764837
0,2025-12-31,24776000000,568000000,1000000,1000000,535000000,2701000000,24208000000,1.358000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2134000000,NaN,7197000000,2030000000,2344000000,NaN,NaN,2390000000,5167000000,NaN,36070000000,NaN,NaN,3431000000,-2704000000,NaN,17579000000,NaN,10714000000,6362000000,385000000,-72.619876,-92.650104,-99.780702,-99.780702,2.099237,-21.550973,-70.749508,-1.594203,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,-164.568835,NaN,-89.886030,-78.447818,-0.085251,NaN,NaN,-38.686506,-91.631033,0.000000,4.614403,0.000000,NaN,-91.300048,-185.165354,0.000000,2.471583,NaN,16.901255,0.299543,0.000000,0.279803,-1462000000,-24.671683,0.409409,0.016256

In [15]:
qtr_income_df.tail(20)

,fiscalDateEnding,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,investmentIncomeNet,netInterestIncome,interestIncome,interestExpense,nonInterestIncome,otherNonOperatingIncome,depreciation,depreciationAndAmortization,incomeBeforeTax,incomeTaxExpense,interestAndDebtExpense,netIncomeFromContinuingOperations,comprehensiveIncomeNetOfTax,ebit,ebitda,netIncome,grossProfit_QoQ,totalRevenue_QoQ,costOfRevenue_QoQ,costofGoodsAndServicesSold_QoQ,operatingIncome_QoQ,sellingGeneralAndAdministrative_QoQ,researchAndDevelopment_QoQ,operatingExpenses_QoQ,investmentIncomeNet_QoQ,netInterestIncome_QoQ,interestIncome_QoQ,interestExpense_QoQ,nonInterestIncome_QoQ,otherNonOperatingIncome_QoQ,depreciation_QoQ,depreciationAndAmortization_QoQ,incomeBeforeTax_QoQ,incomeTaxExpense_QoQ,interestAndDebtExpense_QoQ,netIncomeFromContinuingOperations_QoQ,comprehensiveIncomeNetOfTax_QoQ,ebit_QoQ,ebitda_QoQ,netIncome_QoQ,gross_margin_%,operating_margin_%,net_margin_%
19,2021-03-31,1103000000,2960000000,1857000000,1857000000,399000000,56000000,NaN,707000000,NaN,-217000000.0,217000000.0,217000000,NaN,72000000.0,NaN,542000000,254000000,-36000000,NaN,2.900000e+08,NaN,471000000,1013000000,290000000,-16.057839,-6.240101,0.759631,0.759631,-49.748111,-48.623853,0.000000,35.961538,NaN,-3.125000,10750.000000,-3.982301,NaN,111.764706,NaN,4.835590,-57.807309,-172.000000,NaN,-47.463768,NaN,-43.115942,-24.684015,-44.866920,37.263514,13.479730,9.797297
18,2021-06-30,1278000000,3315000000,2037000000,2037000000,585000000,54000000,NaN,693000000,NaN,-231000000.0,1000000.0,232000000,NaN,76000000.0,NaN,548000000,429000000,68000000,NaN,3.610000e+08,NaN,661000000,1209000000,318000000,15.865820,11.993243,9.693053,9.693053,46.616541,-3.571429,0.000000,-1.980198,NaN,6.451613,-99.539171,6.912442,NaN,5.555556,NaN,1.107011,68.897638,-288.888889,NaN,24.482759,NaN,40.339703,19.348470,9.655172,38.552036,17.647059,9.592760
17,2021-09-30,1989000000,5299000000,3310000000,3310000000,-128000000,1327000000,NaN,2117000000,NaN,-244000000.0,252000000.0,245000000,NaN,47000000.0,NaN,619000000,-326000000,-29000000,NaN,-2.970000e+08,NaN,-81000000,538000000,-297000000,55.633803,59.849170,62.493864,62.493864,-121.880342,2357.407407,0.000000,205.483405,NaN,5.627706,25100.000000,5.603448,NaN,-38.157895,NaN,12.956204,-175.990676,-142.647059,NaN,-182.271468,NaN,-112.254160,-55.500414,-193.396226,37.535384,-2.415550,-5.604831
16,2021-12-31,1347000000,3331000000,1984000000,1984000000,621000000,54000000,311000000.0,726000000,NaN,-230000000.0,231000000.0,231000000,NaN,42000000.0,NaN,571000000,432000000,-139000000,NaN,5.710000e+08,NaN,663000000,1234000000,571000000,-32.277526,-37.139083,-40.060423,-40.060423,-585.156250,-95.930671,42.660550,-65.706188,NaN,-5.737705,-8.333333,-5.714286,NaN,-10.638298,NaN,-7.754443,-232.515337,379.310345,NaN,-292.255892,NaN,-918.518519,129.368030,-292.255892,40.438307,18.643050,17.141999
15,2022-03-31,1444000000,3968000000,2524000000,2524000000,259000000,478000000,NaN,1185000000,NaN,-243000000.0,3000000.0,246000000,NaN,68000000.0,NaN,624000000,81000000,-55000000,NaN,1.360000e+08,NaN,327000000,951000000,136000000,7.201188,19.123386,27.217742,27.217742,-58.293076,785.185185,0.000000,63.223140,NaN,5.652174,-98.701299,6.493506,NaN,61.904762,NaN,9.281961,-81.250000,-60.431655,NaN,-76.182137,NaN,-50.678733,-22.933549,-76.182137,36.391129,6.527218,3.427419
14,2022-06-30,1343000000,4008000000,2665000000,2665000000,504000000,55000000,NaN,839000000,NaN,-256000000.0,15000000.0,271000000,NaN,66000000.0,NaN,601000000,299000000,7000000,NaN,2.920000e+08,NaN,570000000,1171000000,267000000,-6.994460,1.008065,5.586371,5.586371,94.594595,-88.493724,0.000000,-29.198312,NaN,5.349794,400.000000,10.162602,NaN,-2.941176,NaN,-3.685897,269.135802,-112.727273,NaN,114.705882,NaN,74.311927,23.133544,96.323529,33.507984,12.574850,6.661677
13,2022-09-30,1764000000,5228000000,3464000000,3464000000,-44000000,943000000,NaN,1808000000,NaN,-283000000.0,19000000.0,302000000,NaN,85000000.0,NaN,761000000,-261000000,-187000000,NaN,-7.400000e+07,NaN,41000000,802000000,-74000000,31.347729,30.439122,29.981238,29.981238,-108.730159,1614.545455,0.000000,115.494636,NaN,10.546875,26.666667,11.439114,NaN,28.787879,NaN,26.622296,-187.290970,-2771.428571,NaN,-125.342466,NaN,-92.807018,-31.511529,-127.715356,33.741393,-0.841622,-1.415455
12,2022-12-31,1570000000,4016000000,2446000000,2446000000,764000000,51000000,344000000.0,806000000,NaN,-297000000.0,53000000.0,350000000,NaN,129000000.0,NaN,656000000,543000000,73000000,NaN,4.700000e+08,NaN,893000000,1549000000,470000000,-10.997732,-23.182862,-29.387991,-29.387991,-1836.363636,-94.591729,10.610932,-55.420354,NaN,4.946996,178.947368,15.894040,NaN,51.764706,NaN,-13.797635,-308.045977,-139.037433,NaN,-735.135135,NaN,2078.048780,93.142145,-735.135135,39.093625,19.023904,11.703187
11,2023-03-31,1564000000,3966000000,2402000000,2402000000,620000000,148000000,NaN,944000000,NaN,-301000000.0,301000000.0,361000000,NaN,119000000.0,NaN,676000000,378000000,13000000,NaN,3.650000e+08,NaN,739000000,1415000000,365000000,-0.382166,-1.245020,-1.798855,-1.798855,-18.848168,190.196078,0.000000,17.121588,NaN,1.346801,467.924528,3.142857,NaN,-7.751938,NaN,3.048780,-30.386740,-82.191781,NaN,-22.340426,NaN,-17.245241,-8.650742,-22.340426,39.435199,15.632879,9.203227
10,2023-06-30,1576000000,3964000000,2388000000,2388000000,724000000,53000000,NaN,852000000,NaN,-326000000.0,392000000.0,392000000,NaN,128000000.0,NaN,695000000,460000000,51000000,NaN,4.090000e+08,NaN,852000000,1547000000,380000000,0.767263,-0.050429,-0.582848,-0.582848,16.774194,-64.189189,0.000000,-9.745763,NaN,8.305648,30.232558,8.587258,NaN,7.563025,NaN,2.810651,21.693122,292.307692,NaN,12.054795,NaN,15.290934,9.328622,4.109589,39.757820,18.264379,9.586276
9,2023-09-30,1832000000,4702000000,2870000000,2870000000,492000000,536000000,NaN,1340000000,NaN,-365000000.0,433000000.0,433000000,NaN,NaN,NaN,663000000,189000000,-23000000,NaN,2.120000e+08,NaN,624000000,1287000000,212000000,16.243655,18.617558,20.184255,20.184255,-32.044199,911.320755,0.000000,57.276995,NaN,11.963190,10.459184,10.459184,NaN,0.000000,NaN,-4.604317,-58.913043,-145.098039,NaN,-48.166259,NaN,-26.760563,-16.806723,-44.210526,38.962144,10.463632,4.508720
8,2023-12-31,1742000000,3706000000,1964000000,1964000000,791000000,143000000,358000000.0,951000000,NaN,-353000000.0,73000000.0,426000000,NaN,NaN,NaN,687000000,488000000,67000000,NaN,4.210000e+08,NaN,914000000,1601000000,421000000,-4.912664,-21.182476,-31.567944,-31.567944,60.772358,-73.320896,4.069767,-29.029851,NaN,-3.287671,-83.140878,-1.616628,NaN,0.000000,NaN,3.619910,158.201058,-391.304348,NaN,98.584906,NaN,46.474359,24.397824,98.584906,47.004857,21.343767,11.359957
7,2024-03-31,1753000000,4078000000,2325000000,2325000000,245000000,651000000,NaN,1508000000,NaN,-377000000.0,67000000.0,444000000,NaN,NaN,NaN,707000000,-61000000,-113000000,NaN,5.200000e+07,NaN,383000000,1090000000,52000000,0.631458,10.037777,18.380855,18.380855,-69.026549,355.244755,0.000000,58.569926,NaN,6.798867,-8.219178,4.225352,NaN,0.000000,NaN,2.911208,-112.500000,-268.656716,NaN,-87.648456,NaN,-58.096280,-31.917552,-87.648456,42.986758,6.007847,1.275135
6,2024-06-30,1817000000,4336000000,2519000000,2519000000,900000000,37000000,NaN,917000000,NaN,-408000000.0,72000000.0,480000000,NaN,NaN,NaN,747000000,568000000,59000000,NaN,5.090000e+08,NaN,1048000000,1795000000,460000000,3.650884,6.326631,8.344086,8.344086,267.346939,-94.316436,0.000000,-39.190981,NaN,8.222812,7.462687,8.108108,NaN,0.000000,NaN,5.657709,-1031.147541,-152.212389,NaN,878.846154,NaN,173.629243,64.678899,784.615385,41.904982,20.756458,10.608856
5,2024-09-30,1910000000,5201000000,3291000000,3291000000,995000000,37000000,NaN,915000000,NaN,-412000000.0,65000000.0,477000000,NaN,NaN,NaN,729000000,645000000,68000000,NaN,5.770000e+08,NaN,1122000000,1851000000,577000000,5.118327,19.949262,30.647082,30.647082,10.555556,0.000000,0.000000,-0.218103,NaN,0.980392,-9.722222,-0.625000,NaN,0.000000,NaN,-2.409639,13.556338,15.254237,NaN,13.359528,NaN,7.061069,3.119777,25.434783,36.723707,19.130936,11.094020
4,2024-12-31,1738000000,3984000000,2246000000,2246000000,790000000,73000000,NaN,948000000,NaN,-414000000.0,54000000.0,468000000,NaN,NaN,NaN,756000000,411000000,3000000,NaN,4.080000e+08,NaN,879000000,1635000000,408000000,-9.005236,-23.399346,-31.753266,-31.753266,-20.603015,97.297297,0.000000,3.606557,NaN,0.485437,-16.923077,-1.886792,NaN,0.000000,NaN,3.703704,-36.279070,-95.588235,NaN,-29.289428,NaN,-21.657754,-11.669368,-29.289428,43.624498,19.829317,10.240964
3,2025-03-31,1781000000,3811000000,2030000000,2030000000,2134000000,-1269000000,NaN,-353000000,NaN,-256000000.0,45000000.0,301000000,NaN,NaN,NaN,742000000,1940000000,448000000,NaN,1.492000e+09,NaN,2241000000,2983000000,1492000000,2.474108,-4.342369,-9.617097,-9.617097,170.126582,-1838.356164,0.000000,-137.236287,NaN,-38.164251,-16.666667,-35.683761,NaN,0.000000,NaN,-1.851852,372.019465,14833.333333,NaN,265.686275,NaN,154.948805,82.446483,265.686275,46.733141,55.995802,39.149829
2,2025-06-30,1806000000,4543000000,2737000000,2737000000,775000000,36000000,NaN,1031000000,NaN,-465000000.0,39000000.0,504000000,NaN,NaN,NaN,826000000,384000000,-14000000,NaN,3.980000e+08,NaN,888000000,1714000000,398000000,1.403706,19.207557,34.827586,34.827586,-63.683224,-102.836879,0.000000,-392.067989,NaN,81.640625,-13.333333,67.441860,NaN,0.000000,NaN,11.320755,-80.206186,-103.125000,NaN,-73.324397,NaN,-60.374833,-42.541066,-73.324397,39.753467,17.059212,8.760731
1,2025-09-30,2874000000,5750000000,2876000000,2876000000,1432000000,36000000,NaN,1442000000,NaN,-434000000.0,54000000.0,488000000,NaN,NaN,NaN,862000000,1063000000,175000000,NaN,8.880000e+08,NaN,1551000000,2413000000,888000000,59.136213,26.568347,5.078553,5.078553,84.774194,0.000000,0.000000,39.864210,NaN,-6.666667,38.461538,-3.174603,NaN,0.000000,NaN,4.358354,176.822917,-1350.000000,NaN,123.115578,NaN,74.662162,40.781797,123.115578,49.982609,24.904348,15.443478
0,2025-12-31,-412000000,5213000000,5625000000,5625000000,899000000,1197000000,NaN,-1311000000,NaN,NaN,-192000000.0,246000000,NaN,NaN,NaN,807000000,2605000000,682000000,NaN,NaN,NaN,560000000,1367000000,1923000000,-114.335421,-9.339130,95.584145,95.584145,-37.220670,3225.000000,0.000000,-190.915395,NaN,0.000000,-455.555556,-49.590164,NaN,0.000000,NaN,-6.380510,145.061148,289.714286,NaN,0.000000,NaN,-63.894262,-43.348529,116.554054,-7.903319,17.245348,36.888548

In [16]:
pd.DataFrame(stock_financial_dict['EIX']['qtr']).tail(20)

,fiscalDateEnding,gross_margin_%,operating_margin_%,net_margin_%,netIncome,current_ratio,working_capital,longTermDebt_to_workingCp_ratio,debtEquity_ratio,quick_ratio,totalShareholderEquity,operatingCashflow,capitalExpenditures,cashflowFromInvestment,cashflowFromFinancing,ROE_%,liquidation_value,QoQ_gross_margin_%_%,QoQ_operating_margin_%_%,QoQ_net_margin_%_%
19,2021-03-31,37.263514,13.479730,9.797297,259000000,0.561019,-4169000000,-4.836891,3.477483,0.517216,15322000000,72000000,1358000000,-1282000000,1511000000,1.892703,NaN,-10.471148,-46.403644,-41.197590
18,2021-06-30,38.552036,17.647059,9.592760,318000000,0.629687,-2894000000,-7.909813,3.493966,0.577735,15412000000,-1446000000,1235000000,-1130000000,2271000000,2.063327,NaN,3.457867,30.915524,-2.087689
17,2021-09-30,37.535384,-2.415550,-5.604831,-341000000,0.672618,-2934000000,-7.955692,3.792265,0.626646,14841000000,958000000,1355000000,-1242000000,724000000,-2.001213,NaN,-2.637091,-113.688117,-158.427720
16,2021-12-31,40.438307,18.643050,17.141999,545000000,0.637821,-3118000000,-7.751764,3.584844,0.589035,15888000000,427000000,1557000000,-1497000000,939000000,3.593907,NaN,7.733830,-871.793146,-405.843282
15,2022-03-31,36.391129,6.527218,3.427419,110000000,0.632103,-3069000000,-8.135223,3.629013,0.580077,15731000000,792000000,1207000000,-1157000000,205000000,0.864535,NaN,-10.008277,-64.988467,-80.005720
14,2022-06-30,33.507984,12.574850,6.661677,267000000,0.610343,-3609000000,-6.966750,3.636998,0.563053,15774000000,446000000,1501000000,-1471000000,914000000,1.692659,NaN,-7.922659,92.652533,94.364213
13,2022-09-30,33.741393,-0.841622,-1.415455,-101000000,0.595287,-4379000000,-5.742179,3.860187,0.554713,15392000000,874000000,1498000000,-1477000000,713000000,-0.480769,NaN,0.696576,-106.692899,-121.247733
12,2022-12-31,39.093625,19.023904,11.703187,377000000,0.683290,-3277000000,-8.246872,3.874208,0.637479,15621000000,1058000000,1573000000,-5574000000,1124000000,3.008770,NaN,15.862514,-2360.385730,-926.814364
11,2023-03-31,39.435199,15.632879,9.203227,365000000,0.861822,-1156000000,-25.468858,3.917753,0.802056,15648000000,-90000000,1324000000,-1305000000,1316000000,2.332566,NaN,0.873732,-17.825073,-21.361359
10,2023-06-30,39.757820,18.264379,9.586276,409000000,0.840150,-1411000000,-20.857548,3.916735,0.782259,15793000000,802000000,1387000000,-1345000000,-97000000,2.406129,NaN,0.818105,16.833111,4.162117
9,2023-09-30,38.962144,10.463632,4.508720,212000000,0.801484,-1792000000,-16.479911,3.994448,0.745541,15670000000,1834000000,1280000000,-3894000000,-339000000,1.352904,NaN,-2.001308,-42.710167,-52.966935
8,2023-12-31,47.004857,21.343767,11.359957,386000000,0.792161,-1787000000,-16.964745,4.116767,0.730868,15501000000,855000000,1457000000,-1339000000,567000000,2.715954,NaN,20.642379,103.980471,151.955269
7,2024-03-31,42.986758,6.007847,1.275135,11000000,0.996332,-29000000,-1123.310345,4.349064,0.930694,15172000000,1043000000,1279000000,-1276000000,988000000,0.342737,NaN,-8.548263,-71.851984,-88.775179
6,2024-06-30,41.904982,20.756458,10.608856,460000000,1.028765,238000000,139.071429,4.340638,0.964225,15424000000,329000000,1421000000,-1394000000,577000000,2.982365,NaN,-2.516535,245.489118,731.979137
5,2024-09-30,36.723707,19.130936,11.094020,538000000,0.875044,-1063000000,-30.388523,4.254740,0.812390,15663000000,2472000000,1511000000,-1427000000,-1201000000,3.683841,NaN,-12.364340,-7.831400,4.573201
4,2024-12-31,43.624498,19.829317,10.240964,362000000,0.847849,-1284000000,-26.116822,4.358432,0.784098,15565000000,1170000000,1496000000,-1439000000,310000000,2.621266,NaN,18.791107,3.650532,-7.689336
3,2025-03-31,46.733141,55.995802,39.149829,1491000000,0.955979,-342000000,-103.470760,4.188605,0.886601,16622000000,1224000000,1408000000,-1374000000,1374000000,8.976056,NaN,7.125911,182.388954,282.286570
2,2025-06-30,39.753467,17.059212,8.760731,398000000,0.872567,-1015000000,-34.454187,4.192257,0.806905,16686000000,882000000,1712000000,-1628000000,-383000000,2.385233,NaN,-14.935170,-69.534837,-77.622557
1,2025-09-30,49.982609,24.904348,15.443478,889000000,0.820469,-1691000000,-20.389710,4.148003,0.764837,17155000000,2122000000,1504000000,-1491000000,-513000000,5.176333,NaN,25.731446,45.987680,76.280708
0,2025-12-31,-7.903319,17.245348,36.888548,1923000000,0.279803,-1462000000,-24.671683,0.409409,0.016256,17579000000,1572000000,1891000000,-1842000000,93000000,10.939189,NaN,-115.812137,-30.753665,138.861656

In [17]:
# searching & merge process
YoY_EPS_screener = pd.DataFrame()

for symbol in stock_financial_dict.keys():
    annaul_df = pd.DataFrame(
        stock_financial_dict[symbol]['annual']
    )

    annaul_df = annaul_df[['fiscalDateEnding', 'YoY_reportedEPS_%', 'reportedEPS']].rename(
        columns={
            'YoY_reportedEPS_%': f'{symbol}_YoY_reportedEPS_%'
            ,'reportedEPS': f'{symbol}_reportedEPS'
            }
    )
    annaul_df['fiscalDateEnding'] = pd.to_datetime(annaul_df['fiscalDateEnding']).dt.year


    if YoY_EPS_screener.empty:
        YoY_EPS_screener = annaul_df
    else:
        YoY_EPS_screener = pd.merge(
            YoY_EPS_screener
            ,annaul_df
            ,on='fiscalDateEnding'
            ,how='outer'
        )

In [18]:
YoY_EPS_screener

    fiscalDateEnding  EIX_YoY_reportedEPS_%  EIX_reportedEPS
19              2006                    NaN              NaN
18              2007                    NaN              NaN
17              2008                    NaN              NaN
16              2009                    NaN              NaN
15              2010                    NaN              NaN
14              2011                    NaN           3.2100
13              2012              -0.934579           3.1800
12              2013              18.867925           3.7800
11              2014              20.899471           4.5700
10              2015             -10.284464           4.1000
9               2016              -1.707317           4.0300
8               2017              11.166253           4.4800
7               2018              -4.241071           4.2900
6               2019               9.557110           4.7000
5               2020              -4.468085           4.4900
4               2021               2.004454           4.5800
3               2022               1.310044           4.6400
2               2023               2.586207           4.7600
1               2024               3.361345           4.9200
0               2025              33.087398           6.5479

In [19]:
stock_PE_annual_consolidate_df

    fiscalDateEnding  EIX_PE
0               2025    9.17
1               2024   16.23
2               2023   15.02
3               2022   13.71
4               2021   14.90
5               2020   13.99
6               2019   16.04
7               2018   13.23
8               2017   14.12
9               2016   17.86
10              2015   14.44
11              2014   14.33
12              2013   12.25
13              2012   14.21
14              2011   12.90

# SP500 sectors

## SP500 sector ticker

In [ ]:
# Function to get the list of S&P 500 companies and their sectors
def get_sp500_companies():
    # Fetch the S&P 500 company symbols and sectors from a reliable source (e.g., Wikipedia)
    url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
    tables = pd.read_html(url)
    
    # Extract the relevant table containing the company symbols and sectors
    sp500_df = tables[0]
    
    # Return the DataFrame containing S&P 500 companies and sectors
    return sp500_df[['Symbol', 'GICS Sector', 'GICS Sub-Industry']]


# Function to create a dictionary of sectors and sub-sectors
def create_sector_subsector_dict(df):
    sector_subsector_dict = {}
    for index, row in df.iterrows():
        sector = row['GICS Sector']
        subsector = row['GICS Sub-Industry']
        if sector not in sector_subsector_dict:
            sector_subsector_dict[sector] = [subsector]
        else:
            sector_subsector_dict[sector].append(subsector)
    return sector_subsector_dict

# Function to filter the S&P 500 companies by sector
def company_sector_list(df, sector):
    return df[df['GICS Sector'] == sector]['Symbol'].tolist()

def company_sub_sector_list(df, sub_sector):
    return df[df['GICS Sub-Industry'] == sub_sector]['Symbol'].tolist()


# Get the list of S&P 500 companies and their sectors
sp500_df  = get_sp500_companies()

sp500_companies_sectors = sp500_df ['GICS Sector'].value_counts().index
sp500_companies_sub_sectors = sp500_df ['GICS Sub-Industry'].value_counts().index

sector_subsector_dict = create_sector_subsector_dict(sp500_df)


# Function to create a DataFrame from the sector_subsector_dict
def create_sector_dataframe():
    # Create a list to store dictionacompany_sector_listries representing each row of data
    data = []
    
    # Filter the DataFrame to get stocks in the specified sector
    for sector in sp500_companies_sectors:
        sector_stocks_list = company_sector_list(sp500_df, sector)

        # Iterate over the stocks in the sector and create a dictionary for each
        for i, ticker in enumerate(sector_stocks_list, start=1):
            # Create a dictionary for the current stock in the sector
            row_data = {'Sector': sector, 'Ticker': ticker}
            # Append the dictionary to the list
            data.append(row_data)
    
    # Create a DataFrame from the list of dictionaries
    df = pd.DataFrame(data)
    return df


sector_subsector_dict = create_sector_subsector_dict(sp500_df)


sector_ticker_df = create_sector_dataframe()
# sector_ticker_list = sector_ticker_df[sector_ticker_df['Sector'] == 'Consumer Staples']['Ticker'].tolist()

NameError: name 'pd' is not defined

In [ ]:
# Pivot the DataFrame
sp500_pivot_sector_ticker_df = sector_ticker_df.groupby('Sector')['Ticker'].apply(list).reset_index()

# Transpose to get sectors as columns
sp500_pivot_sector_ticker_df = sp500_pivot_sector_ticker_df.set_index('Sector').T

sp500_pivot_sector_ticker_df

Sector,Communication Services,Consumer Discretionary,Consumer Staples,Energy,Financials,Health Care,Industrials,Information Technology,Materials,Real Estate,Utilities
Ticker,"[GOOGL, GOOG, T, CHTR, CMCSA, EA, FOXA, FOX, I...","[ABNB, AMZN, APTV, AZO, BBY, BKNG, BWA, CZR, K...","[MO, ADM, BF.B, BG, CPB, CHD, CLX, KO, CL, CAG...","[APA, BKR, CVX, COP, CTRA, DVN, FANG, EOG, EQT...","[AFL, ALL, AXP, AIG, AMP, AON, APO, ACGL, AJG,...","[ABT, ABBV, A, ALGN, AMGN, BAX, BDX, TECH, BII...","[MMM, AOS, ALLE, AME, ADP, AXON, BA, BR, BLDR,...","[ACN, ADBE, AMD, AKAM, APH, ADI, ANSS, AAPL, A...","[APD, ALB, AMCR, AVY, BALL, CE, CF, CTVA, DOW,...","[ARE, AMT, AVB, BXP, CPT, CBRE, CSGP, CCI, DLR...","[AES, LNT, AEE, AEP, AWK, ATO, CNP, CMS, ED, C..."

In [ ]:
sp500_pivot_sector_ticker_df['Consumer Staples'].iloc[0]

['MO',
 'ADM',
 'BF.B',
 'BG',
 'CPB',
 'CHD',
 'CLX',
 'KO',
 'CL',
 'CAG',
 'STZ',
 'COST',
 'DG',
 'DLTR',
 'EL',
 'GIS',
 'HSY',
 'HRL',
 'K',
 'KVUE',
 'KDP',
 'KMB',
 'KHC',
 'KR',
 'LW',
 'MKC',
 'TAP',
 'MDLZ',
 'MNST',
 'PEP',
 'PM',
 'PG',
 'SJM',
 'SYY',
 'TGT',
 'TSN',
 'WBA',
 'WMT']

In [ ]:
len(sp500_pivot_sector_ticker_df['Consumer Discretionary'].iloc[0])

50

## SP 500 earnings by years

In [ ]:
sp500_eps_df= pd.read_excel('D:\Investment\SP500_sectors\sp500_earnings\sp-500-eps-est.xlsx'
                            ,sheet_name='QUARTERLY DATA')

In [ ]:
sp500_eps_df.columns = [
    'Quarter'
    ,'Ops EPS(Opearting)'
    ,'Reported EPS(GAAP)'
    ,'Div/share'
    ,'Sales/share'
    ,'BVPS'
    ,'CapEx/share'
    ,'Price'
    ,'Divisor'
]

In [ ]:
sp500_eps_df = sp500_eps_df[5::].fillna(0)
sp500_eps_df_no_first = sp500_eps_df \
    .iloc[1:] \
    .sort_values(['Quarter'], ascending=True) \
    .copy()

#####################
# Column enrichment #
#####################
sp500_eps_df['Year'] = pd.to_datetime(sp500_eps_df['Quarter']).dt.year
sp500_eps_df["Month"] = pd.to_datetime(sp500_eps_df['Quarter']).dt.month

# Calculate year end EPS
last_quarter_prices_df = sp500_eps_df[sp500_eps_df["Month"] == 12][["Year", "Price"]]
price_map = dict(zip(last_quarter_prices_df["Year"], last_quarter_prices_df["Price"]))
sp500_eps_df["Yearly price"] = sp500_eps_df["Year"].map(price_map)


# Calculate rolling 4-quarter sum
sp500_eps_df_no_first["Ops EPS(Opearting) TTM"] = sp500_eps_df_no_first["Ops EPS(Opearting)"].rolling(window=4).sum()
sp500_eps_df_no_first["Reported EPS(GAAP) TTM"] = sp500_eps_df_no_first["Reported EPS(GAAP)"].rolling(window=4).sum()
sp500_eps_df_no_first["Div/share TTM"] = sp500_eps_df_no_first["Div/share"].rolling(window=4).sum()


# Merge back with original dataframe
sp500_eps_df = sp500_eps_df.merge(
    sp500_eps_df_no_first[
        [
            "Quarter"
            ,"Ops EPS(Opearting) TTM"
            ,'Reported EPS(GAAP) TTM'
            ,'Div/share TTM'
            ]
        ]
    ,on="Quarter"
    ,how="left"
    )


######################
# Metrics calcuation #
######################
sp500_eps_df['PE TTM Ops'] = sp500_eps_df['Price'] / sp500_eps_df['Ops EPS(Opearting) TTM']
sp500_eps_df['PE TTM GAAP'] = sp500_eps_df['Price'] / sp500_eps_df['Reported EPS(GAAP) TTM']
sp500_eps_df['Earnings yield(Ops)'] = round((sp500_eps_df['Ops EPS(Opearting) TTM'] / sp500_eps_df['Price']) * 100, 2)
sp500_eps_df['Earnings yield(GAAP)'] = round((sp500_eps_df['Reported EPS(GAAP) TTM'] / sp500_eps_df['Price']) * 100, 2)
sp500_eps_df['Div payout ratio(Opearting)'] = round((sp500_eps_df['Div/share TTM'] / sp500_eps_df['Ops EPS(Opearting) TTM']) * 100 ,2)
sp500_eps_df['Div payout ratio(GAAP)'] = round((sp500_eps_df['Div/share TTM'] / sp500_eps_df['Reported EPS(GAAP) TTM']) * 100, 2)
# sp500_eps_df["Ops EPS(Opearting) TTM Growth Rate"] = round(((sp500_eps_df["Ops EPS(Opearting) TTM"] - sp500_eps_df["Ops EPS(Opearting) TTM"].shift(-1)) 
#                                                        / sp500_eps_df["Ops EPS(Opearting) TTM"])*100, 2)
# sp500_eps_df["Reported EPS(GAAP) TTM Growth Rate"] = round(((sp500_eps_df["Reported EPS(GAAP) TTM"] - sp500_eps_df["Reported EPS(GAAP) TTM"].shift(-1)) 
#                                                        / sp500_eps_df["Reported EPS(GAAP) TTM"])*100, 2)


# 1.section: YoY growth rate
sp500_eps_df_yrly_ops_eps = sp500_eps_df.groupby(['Year'])['Ops EPS(Opearting)'].sum().reset_index()
sp500_eps_df_yrly_gaap_eps = sp500_eps_df.groupby(['Year'])['Reported EPS(GAAP)'].sum().reset_index()
sp500_eps_df_yrly_ops_eps['YoY growth rate(Ops)'] = sp500_eps_df_yrly_ops_eps['Ops EPS(Opearting)'].pct_change()
sp500_eps_df_yrly_gaap_eps['YoY growth rate(GAAP)'] = sp500_eps_df_yrly_gaap_eps['Reported EPS(GAAP)'].pct_change()

# Create mapping dictionary: {year: YoY growth}
growth_map_ops_eps = dict(zip(sp500_eps_df_yrly_ops_eps["Year"], sp500_eps_df_yrly_ops_eps["YoY growth rate(Ops)"]))
growth_map_gaap_eps = dict(zip(sp500_eps_df_yrly_gaap_eps["Year"], sp500_eps_df_yrly_gaap_eps["YoY growth rate(GAAP)"]))
yrly_map_ops_eps = dict(zip(sp500_eps_df_yrly_ops_eps["Year"], sp500_eps_df_yrly_ops_eps["Ops EPS(Opearting)"]))
yrly_map_gaap_eps = dict(zip(sp500_eps_df_yrly_gaap_eps["Year"], sp500_eps_df_yrly_gaap_eps["Reported EPS(GAAP)"]))

# Map back to original df
sp500_eps_df["YoY growth rate(Ops)"] = round(sp500_eps_df["Year"].map(growth_map_ops_eps)*100, 2)
sp500_eps_df["YoY growth rate(GAAP)"] = round(sp500_eps_df["Year"].map(growth_map_gaap_eps)*100, 2)
sp500_eps_df["Yearly EPS (Ops)"] = sp500_eps_df["Year"].map(yrly_map_ops_eps)
sp500_eps_df["Yearly EPS (GAAP)"] = sp500_eps_df["Year"].map(yrly_map_gaap_eps)


# 2.section: PE TTM AVG Section
PE_TTM_ops_avg = sp500_eps_df.loc[sp500_eps_df["PE TTM Ops"] != 0, "PE TTM Ops"].mean(skipna=True)
PE_TTM_gaap_avg = sp500_eps_df.loc[sp500_eps_df["PE TTM GAAP"] != 0, "PE TTM GAAP"].mean(skipna=True)
sp500_eps_df['PE TTM Ops AVG'] = round(PE_TTM_ops_avg, 2)
sp500_eps_df['PE TTM GAAP AVG'] = round(PE_TTM_gaap_avg, 2)

# 3. section: PE 5 years rolling average
sp500_eps_df['PE Yrly Ops'] = sp500_eps_df['Yearly price'] / sp500_eps_df["Yearly EPS (Ops)"]
sp500_eps_df['PE Yrly GAAP'] = sp500_eps_df["Yearly price"] / sp500_eps_df["Yearly EPS (GAAP)"]

sp500_eps_df_yrly_ops_PE = sp500_eps_df[sp500_eps_df["PE Yrly Ops"] != 0] \
                            .groupby("Year", as_index=False)["PE Yrly Ops"] \
                            .mean()
sp500_eps_df_yrly_gaap_PE = sp500_eps_df[sp500_eps_df["PE Yrly GAAP"] != 0] \
                            .groupby("Year", as_index=False)["PE Yrly GAAP"] \
                            .mean()

sp500_eps_df_yrly_ops_PE["PE Ops 5Y Avg"] = sp500_eps_df_yrly_ops_PE["PE Yrly Ops"].rolling(window=5, min_periods=1).mean()
sp500_eps_df_yrly_ops_PE["PE Ops 10Y Avg"] = sp500_eps_df_yrly_ops_PE["PE Yrly Ops"].rolling(window=10, min_periods=1).mean()
sp500_eps_df_yrly_gaap_PE["PE GAAP 5Y Avg"] = sp500_eps_df_yrly_gaap_PE["PE Yrly GAAP"].rolling(window=5, min_periods=1).mean()
sp500_eps_df_yrly_gaap_PE["PE GAAP 10Y Avg"] = sp500_eps_df_yrly_gaap_PE["PE Yrly GAAP"].rolling(window=10, min_periods=1).mean()


# Create mapping dictionaries
PE5_ops_map = dict(zip(sp500_eps_df_yrly_ops_PE["Year"], sp500_eps_df_yrly_ops_PE["PE Ops 5Y Avg"]))
PE10_ops_map = dict(zip(sp500_eps_df_yrly_ops_PE["Year"], sp500_eps_df_yrly_ops_PE["PE Ops 10Y Avg"]))
PE5_gaap_map = dict(zip(sp500_eps_df_yrly_gaap_PE["Year"], sp500_eps_df_yrly_gaap_PE["PE GAAP 5Y Avg"]))
PE10_gaap_map = dict(zip(sp500_eps_df_yrly_gaap_PE["Year"], sp500_eps_df_yrly_gaap_PE["PE GAAP 10Y Avg"]))


# Map to quarterly dataframe
sp500_eps_df["PE Ops 5Y Avg"] = sp500_eps_df["Year"].map(PE5_ops_map)
sp500_eps_df["PE Ops 10Y Avg"] = sp500_eps_df["Year"].map(PE10_ops_map)
sp500_eps_df["PE GAAP 5Y Avg"] = sp500_eps_df["Year"].map(PE5_gaap_map)
sp500_eps_df["PE GAAP 10Y Avg"] = sp500_eps_df["Year"].map(PE10_gaap_map)

In [ ]:
sp500_eps_df.head(10)

,Quarter,Ops EPS(Opearting),Reported EPS(GAAP),Div/share,Sales/share,BVPS,CapEx/share,Price,Divisor,Year,Month,Yearly price,Ops EPS(Opearting) TTM,Reported EPS(GAAP) TTM,Div/share TTM,PE TTM Ops,PE TTM GAAP,Earnings yield(Ops),Earnings yield(GAAP),Div payout ratio(Opearting),Div payout ratio(GAAP),YoY growth rate(Ops),YoY growth rate(GAAP),Yearly EPS (Ops),Yearly EPS (GAAP),PE TTM Ops AVG,PE TTM GAAP AVG,PE Yrly Ops,PE Yrly GAAP,PE Ops 5Y Avg,PE Ops 10Y Avg,PE GAAP 5Y Avg,PE GAAP 10Y Avg
0,2025-06-30,0.00,0.00,19.484935,0.000000,0.000000,0.000000,6204.953952,8461.081057,2025,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-75.36,-74.36,57.51,53.89,19.46,24.42,NaN,NaN,22.482021,22.251477,24.771408,25.455504
1,2025-03-31,57.51,53.89,19.372895,488.420003,1197.110200,30.911700,5611.852607,8473.831556,2025,3,NaN,236.24,216.69,76.145301,23.754879,25.898069,4.21,3.86,32.23,35.14,-75.36,-74.36,57.51,53.89,19.46,24.42,NaN,NaN,22.482021,22.251477,24.771408,25.455504
2,2024-12-31,61.21,57.69,19.810500,508.588989,1178.567800,34.471600,5881.627648,8467.894518,2024,12,5881.627648,233.36,210.17,74.832255,25.204095,27.985096,3.97,3.57,32.07,35.61,9.29,9.22,233.36,210.17,19.46,24.42,25.204095,27.985096,24.124493,22.061110,27.797731,25.272067
3,2024-09-30,59.16,51.99,18.680400,501.354000,1166.346100,30.891700,5762.484883,8451.342154,2024,9,5881.627648,226.05,200.27,73.400300,25.492081,28.773580,3.92,3.48,32.47,36.65,9.29,9.22,233.36,210.17,19.46,24.42,25.204095,27.985096,24.124493,22.061110,27.797731,25.272067
4,2024-06-28,58.36,53.12,18.281506,488.705399,1139.314000,28.457100,5460.482621,8395.388376,2024,6,5881.627648,219.14,195.93,71.975800,24.917781,27.869559,4.01,3.59,32.84,36.74,9.29,9.22,233.36,210.17,19.46,24.42,25.204095,27.985096,24.124493,22.061110,27.797731,25.272067
5,2024-03-28,54.63,47.37,18.059849,471.949169,1116.727900,27.060700,5254.354401,8388.772132,2024,3,5881.627648,215.62,191.39,70.824826,24.368585,27.453652,4.10,3.64,32.85,37.01,9.29,9.22,233.36,210.17,19.46,24.42,25.204095,27.985096,24.124493,22.061110,27.797731,25.272067
6,2023-12-29,53.90,47.79,18.378545,490.201506,1106.214712,30.133461,4769.829411,8394.128747,2023,12,4769.829411,213.53,192.43,70.303692,22.337983,24.787348,4.48,4.03,32.92,36.53,8.42,11.39,213.53,192.43,19.46,24.42,22.337983,24.787348,23.196177,21.362416,26.833653,24.485973
7,2023-09-29,52.25,47.65,17.255900,468.524082,1076.237542,27.013050,4288.054123,8380.848066,2023,9,4769.829411,210.00,184.25,69.313136,20.419305,23.273021,4.90,4.30,33.01,37.62,8.42,11.39,213.53,192.43,19.46,24.42,22.337983,24.787348,23.196177,21.362416,26.833653,24.485973
8,2023-06-30,54.84,48.58,17.130532,462.132679,1061.913100,25.961900,4450.381312,8350.369620,2023,6,4769.829411,208.10,181.01,68.714936,21.385782,24.586384,4.68,4.07,33.02,37.96,8.42,11.39,213.53,192.43,19.46,24.42,22.337983,24.787348,23.196177,21.362416,26.833653,24.485973
9,2023-03-31,52.54,48.41,17.538715,451.437952,1045.266400,25.460100,4109.312445,8357.127040,2023,3,4769.829411,200.13,175.17,68.211442,20.533216,23.458997,4.87,4.26,34.08,38.94,8.42,11.39,213.53,192.43,19.46,24.42,22.337983,24.787348,23.196177,21.362416,26.833653,24.485973

In [ ]:
sp500_eps_df.to_excel('D:\Investment\SP500_sectors\sp500_earnings\sp-500-eps-est-hist.xlsx')

# Stock PE by years by tickers

In [ ]:
stock_financial_dict = {} # the dict will store ticker as key, the string value of 'annual_df' and 'qtr_df' as nested key, actual json as value
stock_PE_annual_consolidate_df = pd.DataFrame()

ticker_symbols = [
'MNST'
,'KO'
,'KDP'
,'PEP'
 ]
# ticker_symbols = electric_utility_symbols
PE_yr_range = 10 # test for 'X' years PE

In [ ]:

# storage process
for j, symbol in enumerate(ticker_symbols):
    print(j, symbol)
    # # COMPANY OVERVIEW
    # # replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
    # url = f'https://www.alphavantage.co/query?function=OVERVIEW&symbol={symbol}&apikey={alpha_vantage_api_key}'
    # r = requests.get(url)
    # data = r.json()


    # for key, value in data.items():
    #     if key  == 'MarketCapitalization':
    #         stock_mkt_cap = float(value)



    # STOCK SPLIT FACTOR section
    url = f'https://www.alphavantage.co/query?function=SPLITS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'data':
            if len(value) > 0:
                stock_split_record_df = pd.DataFrame(value)
                stock_split_record_df['split_factor'] = pd.to_numeric(stock_split_record_df['split_factor'], errors='coerce') # change split_factor series to numeric data
                stock_split_record_df['effective_date'] = pd.to_datetime(stock_split_record_df['effective_date'])
            else:
                # Use pandas index assign instead of direct assign value
                stock_split_record_df = pd.DataFrame({
                'split_factor': [1],
                'effective_date': [datetime.today()]
            })



    # Monthly quote section
    url = f'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'Monthly Time Series':
            Monthly_stock_df = pd.DataFrame(value)


    Monthly_stock_df = Monthly_stock_df.transpose()
    Monthly_stock_df.index = pd.to_datetime(Monthly_stock_df.index)


    filter_1 = (Monthly_stock_df.index.year.isin(range((datetime.today().year - PE_yr_range) ,datetime.today().year)))
    filter_2 = (Monthly_stock_df.index.month == 12) # month = 12 to get the year end closing price

    selected_cols = [
        '4. close'
    ]

    Monthly_stock_df = Monthly_stock_df[
        filter_1
        & filter_2
    ][selected_cols]

    # Rename columns
    Monthly_stock_df.rename(
        columns={
            '4. close': 'stock_price'
            }
        ,inplace=True
        )

    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].astype(str).apply(lambda x: float(x))
    Monthly_stock_df["stock_price"] = Monthly_stock_df["stock_price"].round(2)

    # modify stock price based on stock split
    for year_i in Monthly_stock_df.index.year:
        for year_j in stock_split_record_df['effective_date'].dt.year:
            if year_i == year_j:

                # stock price to divided the split factor
                Monthly_stock_df.loc[Monthly_stock_df.index.year < year_j, 'stock_price'] /= (stock_split_record_df['split_factor'][stock_split_record_df['effective_date'].dt.year == year_j].values[0])
    


    # Earning section
    # past earnings from alpha vintage API
    url = f'https://www.alphavantage.co/query?function=EARNINGS&symbol={symbol}&apikey={alpha_vantage_api_key}'
    r = requests.get(url)
    data = r.json()

    for key, value in data.items():
        if key == 'annualEarnings':

            selected_cols = [
                'fiscalDateEnding'
                ,'reportedEPS'
            ]

            annualEPS_df = pd.DataFrame(value) # tranpose the dataframe and sub select selected cols


            annualEPS_df['fiscalDateEnding'] = pd.to_datetime(annualEPS_df['fiscalDateEnding']).dt.year

            annualEPS_df = annualEPS_df[
                annualEPS_df['fiscalDateEnding'].isin(
                    range(
                        (datetime.today().year - PE_yr_range) 
                        ,datetime.today().year
                            )
                            )
                            ]

            # Convert the column to decimal type
            for col in selected_cols:
                if col in ['reportedEPS']:
                    annualEPS_df[f'{col}'] = annualEPS_df[f'{col}'].astype(str).apply(lambda x: float(x))

                else:
                    continue
            # clean annualEPS_df
            annualEPS_df = annualEPS_df.sort_values('reportedEPS', ascending=False).drop_duplicates('fiscalDateEnding')
            annualEPS_df = annualEPS_df.sort_values('fiscalDateEnding', ascending=False).reset_index(drop=True)

            # calculate PE
            annualEPS_df["PE"] = Monthly_stock_df["stock_price"].values / annualEPS_df['reportedEPS'].values


    ####################
    ### Consolidated ###
    ####################

    # annual PE df
    if stock_PE_annual_consolidate_df.empty:
        stock_PE_annual_consolidate_df['fiscalDateEnding'] = annualEPS_df['fiscalDateEnding']

    stock_PE_annual_consolidate_df[f'{symbol}_PE'] = annualEPS_df["PE"].round(2)


stock_PE_annual_consolidate_df['industry_avg_PE'] = stock_PE_annual_consolidate_df.iloc[:, 1:].sum(axis=1) / (stock_PE_annual_consolidate_df.shape[1] -1)  # Sum by row

0 MNST
1 KO
2 KDP
3 PEP

In [ ]:
stock_PE_annual_consolidate_df

   fiscalDateEnding  MNST_PE  KO_PE  KDP_PE  PEP_PE  industry_avg_PE
0              2024    43.44  26.72   23.97   24.53          29.6650
1              2023    36.46  21.91   18.61   22.29          24.8175
2              2022    22.76  25.65   21.23   26.61          24.0625
3              2021    18.68  25.41   23.04   27.79          23.7300
4              2020    17.25  28.12   22.86   26.87          23.7750
5              2019    15.35  26.23   23.73   24.76          22.5175
6              2018    13.67  22.66    8.90   19.55          16.1950
7              2017    22.77  24.02   22.11   23.20          23.0250
8              2016    17.05  21.71   20.61   29.98          22.3375
9              2015    25.08  21.48   23.18   21.91          22.9125

## Appendix

In [ ]:
# Consumer Staples

ticker_symbols = [
    'MO',
    'ADM',
    # 'BF.B', # DATA ISSUE
    'BG',
    'CPB',
    'CHD',
    'CLX',
    'KO',
    'CL',
    'CAG',
    'STZ', # !!
    'COST',
    'DG',
    'DLTR', # !!
    'EL',
    'GIS',
    'HSY',
    'HRL',
    'K',
    'KVUE',
    'KDP',
    'KMB',
    'KHC',
    'KR', # DATA ISSUE
    'LW',
    'MKC', # DATA ISSUE
    'TAP',
    'MDLZ',
    'MNST',
    'PEP',
    'PM',
    'PG',
    'SJM',
    'SYY',
    'TGT', # !!
    'TSN', # !!
    'WBA', # DATA ISSUE
    'WMT'
]

In [ ]:
# Energy

ticker_symbols = [
'APA',
 'BKR', # !! HIGH PE, LOW PROFITABILITY, HIGH FORECAST,  BUT CANNOT BEAT FORECAST, 总结与TRGP类似, 基本面更稳妥, 盈利预期高, 有待考证
 'CVX',
 'COP',
 'CTRA',
 'DVN',
 'FANG',
 'EOG',
 'EQT',
 'XOM',
 'HAL', # !!!! 与SLB类似
 'HES', # !  HIGH PE, UNDERVALUE, 市场炒作高预期, 2024表现强劲, 已经被超热了
 'KMI',
 'MRO', # PROFITABILITY, STEADY GROWTH FORECAST, AND CAN BEAT FORECAST, 总结基本面良好，与HAL类型相似, 市场炒作热度比HAL更高, 值得研究
 'TRGP', # !！ HGIH PE
 'MPC',
 'OXY',
 'OKE', # !!
 'PSX',
 'SLB', # !!! A BIT HIGH PE, GOOD ROE, MED, HIGH ROE, RELATIVE MORE DEBT THAN EQUITY, LOW PROFITABILITY, HIGH FORECAST, BUT CANNOT BEAT FORECAST, 总结基本面一般, 但是盈利预期非常高, 有待考证
 'VLO',
 'WMB'
 ]

In [ ]:
electric_utility_symbols = [
'CEPU'
,'OTTR'
,'PAM'
,'SO' ##
,'DUK'
,'NRG'
,'IDA'
,'DTE' #
,'CEG' ##
,'SRE'
,'ETR'
,'PEG'
,'MGEE'
,'LNT'
,'BKH'
]